TIBCOSoftware/snappydata

snappy-tools/src/main/scala/io/snappydata/tools/LeaderLauncher.scala
snappy-tools/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

Users trying out will likely follow our simple guide and we cannot hope to have them read everything to understand the fine points of heap-size, overflow etc. Ideally we should also be setting ASYNC PERSISTENCE by default at least for column tables in my opinion, but not addressing that in this PR. Is trivial to add if team agrees.
* set eviction policy to OVERFLOW by default for column tables (including sample tables)
* skip default heap-size setting for lead node
Also see related PR on snappy-store https://github.com/SnappyDataInc/snappy-store/pull/17
With these settings I have tested full dataset load with default scripts, and then loading even more data which causes overflow just fine without affecting the system usability. Load performance goes down for second one by ~20% primarily …

SNAP-505: Changes to fix OOME cases with defaults

---

snappy-core/build.gradle
snappy-core/src/main/scala/io/snappydata/Literals.scala
snappy-core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
snappy-core/src/main/scala/org/apache/spark/sql/columnar/ExternalStoreUtils.scala
snappy-core/src/main/scala/org/apache/spark/sql/columnar/JDBCAppendableRelation.scala
snappy-core/src/main/scala/org/apache/spark/sql/execution/ConnectionPool.scala
snappy-core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
snappy-core/src/main/scala/org/apache/spark/sql/store/JDBCSourceAsStore.scala
snappy-dunits/src/test/scala/io/snappydata/dunit/cluster/QueryRoutingDUnitTest.scala
snappy-tools/build.gradle
snappy-tools/src/main/scala/io/snappydata/Utils.scala
snappy-tools/src/main/scala/org/apache/spark/sql/columntable/ColumnFormatRelation.scala
snappy-tools/src/main/scala/org/apache/spark/sql/rowtable/RowFormatRelation.scala
snappy-tools/src/main/scala/org/apache/spark/sql/rowtable/RowFormatScanRDD.scala
snappy-tools/src/main/scala/org/apache/spark/sql/store/impl/JDBCSourceAsColumnarStore.scala

* moved all ResultSet iteration code into a ResultSetIterator class taken mostly from InternalRowIteratorOnRS
for cleanly closing it even if not iterated fully (like for LIMIT); also simplified handling a bit
and now both InternalRowIteratorOnRS and CachedBatchIteratorOnRS extend it. This fixes SNAP-608
* added a test section in existing QueryRoutingDUnitTest.testSNAP193 to check the fix
* moved all disparate pool property handling (max/idle sizes etc) into ExternalStoreUtils.getAllPoolProperties
where the respective properties will not be overwritten if explicitly provided
* removed DriverRegistry.register call in every ConnectionPool get and instead have it only in few places
like creation of Relation objects on driver, and ExternalStoreUtils.getConnector call on executors
* updated …

Fixes and refactoring for SNAP-608

---

build.gradle
snappy-core/build.gradle
snappy-dunits/src/test/scala/io/snappydata/dunit/cluster/QueryRoutingDUnitTest.scala
snappy-tools/build.gradle
snappy-tools/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala

* use the correct index into the datatype array and not the current group index
* simplified the logic of splitting into groups of 8 to be just /8 and %8 to go with corresponding changes in snappy-store; updated snappy-store link for (https://github.com/SnappyDataInc/snappy-store/pull/33)
* added test for SNAP-607 in QueryRoutingDUnitTest.testSNAP193_608 and also enabled the test for SNAP-609
Also see https://github.com/SnappyDataInc/snappy-store/pull/33 for corresponding PR on snappy-store.

Fix the datatype mismatch issue when number of cols > 8 (SNAP-607)

---

docs/architecture.md

I suggest we do not split words at the end of lines because it makes the docs harder to maintain. Each time we add / remove something we need to go through the entire document and make sure that the splitted words are not sitting in the middle of a line.

Typos, spacings & splitting words

---

snappy-core/build.gradle
snappy-core/src/main/scala/org/apache/spark/sql/streaming/SchemaDStream.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/StreamSqlHelper.scala
snappy-core/src/main/scala/org/apache/spark/streaming/SnappyStreamingContext.scala
snappy-core/src/main/scala/org/apache/spark/streaming/api/JavaSnappyStreamingContext.scala
snappy-core/src/test/java/org/apache/spark/streaming/JavaSnappyStreamingContextSuite.java
snappy-core/src/test/scala/org/apache/spark/streaming/SnappyStreamingContextSuite.scala

a) added JavaSnappyStreamingContext: This will ease the usage of SnappyStreamingContext from Java. User does not have to maintgain two instance to work with methods from JavaStreamingContext and SnappyStreamingContext.
b) Added helper methods forEachDataFrame in SchemaDStream for Java.
c) Added test.
Added Junit test to test all Java APIs
NA

SnappyStreamingContext Java API

---

core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappyImplicits.scala
core/src/main/scala/org/apache/spark/sql/aqp/SnappyContextDefaultFunctions.scala
core/src/main/scala/org/apache/spark/sql/snappyParsers.scala
core/src/main/scala/org/apache/spark/sql/sources/StoreStrategy.scala

Avoid overloading the InsertIntoTable for puts into row tables else primary key violations are never detected for bulk inserts.
Uses reflection for DataWriter implicit putInto method since DataFrame is private (and not exposed at all).
Existing tests like RowTableTest that use putInto.
Fix to other part of SNAP-677 in #215

[SNAP-677] Create a separate PutIntoTable plan for PUT operations

---

core/src/test/scala/org/apache/spark/sql/store/SnappyJoinSuite.scala

Changed SnappyJOinSuite to disable broadcast hash join. After fixing sizes for snappy relations the small sizes of tests will always cause a broadcast hash join
ran precheckin
NA

Fixed SnappyJoinSuite to not allow broadcasthash join .

---

core/src/main/scala/io/snappydata/impl/SparkShellRDDHelper.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala
tests/dunit/src/test/scala/io/snappydata/dunit/cluster/ClusterManagerTestBase.scala
tests/dunit/src/test/scala/io/snappydata/dunit/externalstore/ExternalShellDUnitTest.scala

- Partial fix for SNAP-652. Buckets with empty host-list (network servers) are given other buckets host-list for executors to process them on. See Other PRs section for the other part of the fix.
- Added a unit test for remote iteration in both the - unified and split cluster - modes.
- precheckin
- New dunit test: ExternalShellDUnitTest.testRemoteIteratorSNAP652()
- https://github.com/SnappyDataInc/snappy-store/pull/52

SNAP-652 - Buckets with empty host-list are provided with other hosts.

---

build.gradle
examples/build.gradle
examples/src/main/python/AirlineDataPythonApp.py
python/pyspark/sql/snappy/context.py
python/pyspark/sql/snappy/tests.py

added the python example under the runQuickstart  target
change the gradle build  to build the new python files
smalll correction in update API
precheckin clean
NO 
added the python example under the runQuickstart  target
change the gradle build  to build the new python files
smalll correction in update API

Added quickstart for snappy python api

---

build.gradle
cluster/build.gradle
cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/ClusterCallbacksImpl.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/io/snappydata/impl/ComplexTypeSerializerImpl.scala
core/src/main/scala/io/snappydata/impl/SparkShellRDDHelper.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/collection/WrappedInternalRow.scala
core/src/main/scala/org/apache/spark/sql/collection/WrappedRow.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/store/CodeGeneration.scala

This adds support for serialization and deserialization of complex types (ARRAY, MAP, STRUCT) from JDBC clients for column tables. The storage in tables is as BLOB in the table and as returned in query results (or for inserts), so this is needed to allow both inserts from JDBC or get results properly instead of as a serialized blob.
- Added new callback class implementation ComplexTypeSerializerImpl to allow serializing ARRAY, MAP, STRUCT types over a JDBC client connection that is compatible with Spark serialized forms as stored in BLOBs in GemXD
- the main code is in the new methods added in CodeGeneration that generate code for the serialization portion while deserialization is handled
- use CodeGeneration of serialization code for complex types with handling in SparkSQLExecuteImpl
- …

[SNAP-750] Serialization of complex types from JDBC

---

docs/jobs.md
python/pyspark/sql/snappy/context.py

updated jobs.md to show the python api
added allowExisting parameter in the create table
executed tests.py for sql test
No
added allowExisting parameter in the create table

updated jobs.md to show the python api

---

build.gradle
docs/jobs.md

Added required details on how to submit a python job in split cluster mode
specified the example
updated the build.gradle to copy the files in python/examples so that
it can be use in doc easily
clean build
executed :runQuickstart
NO

doc update - python job execution

---

core/src/main/scala/io/snappydata/SnappyStoreTableSizeProviders.scala

instead of calling  function on all server it should be called only on datastore 
clean precheckin
No

Bucket size should be calculated only for the datastores

---

build.gradle
core/build.gradle
dtests/build.gradle

Addition of packageTests task to dtests archives enables the "-tests" jar to be published in local and remote maven.
- moved the dangling copy task in dtests/build.gradle inside testsClass.doLast
- also moved the download plugin separately into core so as to not conflict with
store/native declaration (which runs both as sub-project or independent project)
Checked publishLocal that it does place the gemfirexd-scala-tests...-tests jar in local m2 repository.
NA

[SNAP-837] Add packageTests to dtests archives to enable publishing of tests jar

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala

disabling the concurrency checks for the row buffers so that tombstone creation can be avoided.
Before table creation if this method can be used to check if the table
is column table or not simply by looking the entry into the store.
currently it contains hack for default schema but in next commit will
fix  this issue by setting the default schema
precheckin
Yes.
https://github.com/SnappyDataInc/snappy-store/pull/74
Before table creation if this method can be used to check if the table
is column table or not simply by looking the entry into the store.
currently it contains hack for default schema but in next commit will
fix …

helper method to check if relation exists in store

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/cluster/sample.conf
dtests/src/test/java/io/snappydata/hydra/concStreamingWithAirlineDataQueries.conf
dtests/src/test/java/io/snappydata/hydra/serialStreamingWithAirlineDataQueries.conf

- Added support for collecting stats in the framework
- Modified the existing tests to use new methods for creating the configuration data for writting to the respective files under conf directory
- Added a check if in case appPropsForJobServer parameter is not provided in conf file. The method should use default APP_PROPS in this case
Verified the changes by running sample.bt
No

Added support for collecting stats in the framework

---

.github/PULL_REQUEST_TEMPLATE
ReleaseNotes.txt
dtests/build.gradle

* Renaming gemfirexd* jars to snappydata-store* jars.
* Adding ReleaseNotes.txt to keep a record of changes
that may need to be published.
* Added a section in GitHub PR template to update
ReleaseNotes.txt
./gradlew clean buildAll
https://github.com/SnappyDataInc/snappy-store/pull/81

* Renaming gemfirexd* jars to snappydata-store* jars.

---

cluster/build.gradle
core/build.gradle
dtests/build.gradle
dunit/build.gradle

* Correcting the artifact names from snappydata-store* to
gemfirexd* in various build.gradle files.
* In earlier commits, only jar names were renamed to
snappydata-store-* and not artifact names.
* Fixes the issue of './gradlew precheckin -Pstore' not running
unit tests of snappy-store.
./gradlew precheckin (running)
NA
NA

Gradle script fixes

---

cluster/sbin/snappy-nodes.sh

Currently the order of stopping servers is as specified in /conf/servers file. We use the same order during ./sbin/snappy-start-all.sh as well, as a result of this the last server stopped is also the last server started.
Changes made to stop the servers in reverse order as specified in /conf/servers.
Verified changes with running snappy-start-all, snappy-stop-all and snappy-status-all .
NA
No

Reverse the order of stopping servers in ./sbin/snappy-stop-all.sh

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataJobs.conf
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataQueries.conf
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataQueriesAndJobs.conf
dtests/src/test/java/io/snappydata/hydra/cluster/sample.inc
dtests/src/test/java/io/snappydata/hydra/cluster/sampleLeadHA.conf
dtests/src/test/java/io/snappydata/hydra/cluster/sampleSplitMode.conf
dtests/src/test/java/io/snappydata/hydra/concStreamingWithAirlineDataQueries.conf
dtests/src/test/java/io/snappydata/hydra/serialStreamingWithAirlineDataQueries.conf

- Added support to set log-level while generating logs for snappy members.
- Added support in hydra to wait for a job completion instead of relying on waitTime parameter.
- Removed obsolete methods from SnappyTest
Verified the changes by running sample.conf test
NA
No

Added support in hydra to wait for a job completion instead of relying on waitTime parameter

---

core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/aqp/SnappyContextDefaultFunctions.scala
core/src/main/scala/org/apache/spark/sql/aqp/SnappyContextFunctions.scala

sql method has been overridden now in snappycontext (from its base class sqlContext).
precheckin
No
https://github.com/SnappyDataInc/snappy-aqp/pull/79

Override sql method in sqlContext and added same in SnappyContext.

---

cluster/build.gradle
cluster/src/main/scala/io/snappydata/cluster/ExecutorInitiator.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
core/build.gradle
core/src/main/scala/io/snappydata/impl/SparkShellRDDHelper.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/execution/CompactExecRowToMutableRow.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/CachedBatchCreator.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/CachedBatchHolder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCSourceAsStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/execution/datasources/StoreDataSourceStrategy.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala
dtests/build.gradle

- CachedBatch creation: Use direct AbstractCompactExecRow.getAs* calls to get final java
values/objects instead of expensive ExecRow.getColumn().get* calls that create intermediate DVDs
- CachedBatch creation: avoid switch on DataType+metadata for every row. Instead cache the end types
and use a fast switch on ints (code generation might be overkill and may not buy much)
- Skip stats object (avoids its serialization/deserialization cost) for now in CachedBatch creation
since it is not being used
- Use SparkShellRowRDD for split mode execution over row tables (currently only
done for row buffer of a column table)
- Push down only those filters to row tables that can use indexes.
- Added support for push down of more filters like IN, AND, OR, LIKE for
row tables (those that can use indexes) …

[SNAP-950] Multiple optimizations seen during profiling

---

cluster/src/dunit/scala/io/snappydata/cluster/DDLRoutingDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

- corrected formatting for PERSISTENT, OFFHEAP and SERVER_GROUPS in proper
format as expected by snappydata-store
- split the PERSISTENT property into a new DISKSTORE which just specifies
the diskstore name; former specifies async/sync persistence or whether it on/off
- don't access numPartitions in ColumnFormatRelation.destroy else it causes
a RegionDestroyedException in case it is invoked to cleanup create table failure
- added dunit test in DDLRoutingDUnitTest to check for cases of exception for
above clauses as well as when those are proper (no SERVER_GROUPS test yet)
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/commit/6207f0f407ea8a2fbfd67d9ce0da24f5ccd524df has the store side changes

[SNAP-961] Fix passing of some DDL extension clauses

---

cluster/src/dunit/scala/io/snappydata/HiveMetastoreClientAccessDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerTestBase.scala
cluster/src/dunit/scala/io/snappydata/externalstore/ColumnTableDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/externalstore/ExecutorMessageDUnitTest.scala

Fixed the TaskNotSerializable Exception  in the AQP test cases
aqp dunit and cluster dunits
started with the same locator port.

 saved the locURL so that later server can be

---

core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyImplicits.scala
core/src/main/scala/org/apache/spark/sql/collection/GenerateFlatIterator.scala
core/src/main/scala/org/apache/spark/sql/collection/SegmentMap.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/CachedBatchHolder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/LocalJoin.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/rdds.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/sources/jdbcExtensions.scala
core/src/main/scala/org/apache/spark/sql/store/CodeGeneration.scala
core/src/main/scala/org/apache/spark/sql/store/StoreInitRDD.scala

- add code generation for LocalJoin (some taken from BroadcastHashJoinExec)
- the build-side replicated table RDD is not code generated due to WholeStageCodegen
limitation of passing upto 2 RDDs; instead it is passed as reference object and
normal RDD.iterator is opened to consume and create a HashedRelation
- added a HashedRelationCache which expires after configured time (10secs by default)
of no access; also invalidate entire cache in case of any insert/update/delete
to replicated tables (added flag to store side to mark such user regions)
- added code generation for PartitionedPhysicalRDD like a simple row source;
going forward this can be changed to batch source once spark's PRs for InMemoryScan
batching are merged (SPARK-16196, SPARK-14098)
- pass in source rdd.schema in …

 [SNAP-1000][SNAP-1001] Code generation for LocalJoin, PartitionedPhysicalRDD

---

build.gradle
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala

As per SNAP-1007, this primarily adds support for non-reserved keywords which are not allowed in some places in the SQL grammar where otherwise any identifier is allowed.
- marked all keywords as either reserved or non-reserved
- added a "strictIdentifier" which can be neither of reserved or non-reserved;
mark all aliases to use "strictIdentifier" (but identifier when with AS)
- refactored to add "commaSep" rule for all uses of comma followed by whitespace
- marked CAST, CURRENT_DATE/TIMESTAMP as reserved due to ambiguities otherwise
- some formatting corrections
precheckin (no new failures)
NA
NA

[SNAP-1007] Add support for non-reserved keywords

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala

Test enhanced to show that update/delete on column tables are unsupported.

Modified a test to add testing for unsupported op for update/delete.

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyHiveMetaStoreEventListener.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala

+ Registered SnappyHiveMetaStoreEventListener and process onDropTable callback in it (invoked when table dropped from Hive metastore). This callback will be invoked on either embedded snappy lead or external cluster driver (i.e depending on from where the table is dropped)
+ When a table is dropped in on external cluster driver send a message (SnappyRemoveCachedObjectsFunction) to all nodes in embedded cluster to do the clean up. Similarly send a message from embedded lead to external driver if table dropped in embedded mode
Modified SplitClusterDUnitTest to assert that cached relation is removed from SnappyStoreHiveCatalog after a table drop from external table (in testColumnTableCreation())
Ran precheckin(known failures in streaming tests and ColumnTableDUnitTest#testTableCreationWithHA …

Changes for SNAP-653

---

cluster/src/dunit/scala/org/apache/spark/DynamicJarInstallationDUnitTest.scala
cluster/src/main/scala/org/apache/spark/util/SnappyUtils.scala

SNAP-1018 use install_jar_bytes/replace_jar_bytes procedures to load the jar to the store so that jar could be loaded to all the servers in the cluster regardless of the local availability of jar.
manual testing
NO
SNAP-1018 use install_jar_bytes/replace_jar_bytes procedures to load the jar to the store so that jar could be loaded to all the servers in the cluster regardless of the local availability of jar.

SNAP-1018 use install_jar_bytes/replace_jar_bytes

---

core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableBatchInsertTest.scala

* As per the jira SNAP-959 when we execute "Create table as Select" statement with column alias the column alias name should be used to create and insert the data in the table. To fix this issue we used StructField.name instead of StructField.metadata.name as StructField.name contains the column alias name
- Written scala test for this fix and ran precheckin.All test related to this fix passed
No
N/A

[SNAP-959] Fix for SNAP-959

---

core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/store/StoreInitRDD.scala

Fixing a logical bug which was showing up when the number of servers were high ( 6 or more ). The issue was in iterating the keyset of a map.
Patch from Sumedh.
Explanation from him:
The keySet.zipWithIndex will create another set which can be hashed differently from original set due to different capacities (which is why error with only some number of servers). The zipWithIndex will be an iterator on the original set assigning indexes in its iteration order, while the numberedPeers.map will be iterator on the new set that can be in different order if the capacities of the two are different. So numberedPeers.map iteration can return something like (part1, 1), (part0, 0), (part2, 2)
But then the toArray will assume it is in order and return part1 at index 0, part0 at index 1 and so on. One …

Fix for SNAP-1049

---

cluster/src/dunit/scala/io/snappydata/cluster/StringAsVarcharDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala

* Remove changes in primitiveType() which were parsing STRING as CharType instead of StringType.
* Instead do it in columnCharType() which affects only the snappy DDL path.
* Ran precheckin -Pspark. No new failures.
NA

SNAP-1113: Remove changes in primitiveType() for parsing STRING as CharType

---

cluster/src/dunit/scala/io/snappydata/cluster/SnappyTableStatsProviderDUnitTest.scala
core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

SnappyRegionStat is not serializable anymore. Fixed the test so that it does not create an RDD of SnappyRegionStat for test verifacation purpose
executed the SnappyRegionStat DUnit test
yes.
https://github.com/SnappyDataInc/snappy-store/pull/121

Fix the test for serialization issue.

---

build.gradle
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/TPCETrade.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala

- Spark 2.0.2 merge
- Added new Analyzer rule AnalyzeDMLExternalTables.
- This rule converts UnresolvedRelation and eliminate SubqueryAliases to convert into LogicalRelation
- For DML statements, added new RunnableCommand
- Bumped up Spark's version to 2.0.2 from 2.0.0
Spark PR https://github.com/SnappyDataInc/spark/pull/23

Spark 2.0.2 merge

---

cluster/src/test/scala/org/apache/spark/sql/NWQueries.scala
dtests/src/resources/scripts/northWind/nw_queries.sql
dtests/src/test/scala/io/snappydata/hydra/northwind/NWQueries.scala

- Removed the "a." qualification in the ORDER BY clause from Q36
- Enabled Q36 in northWind dunit and scala test
Verified the changes by running northWind.bt, northwind dunit and scala test
NA
No

Fix for SNAP-1183

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/cluster/startEmbeddedModeCluster.conf
dtests/src/test/java/io/snappydata/hydra/cluster/stopEmbeddedModeCluster.conf
dtests/src/test/java/io/snappydata/hydra/distJoin/distJoinWithServerHA.conf
dtests/src/test/java/io/snappydata/hydra/installJar/DynamicJarLoadingTest.java
dtests/src/test/java/io/snappydata/hydra/installJar/TestUtils.java
dtests/src/test/java/io/snappydata/hydra/installJar/dynamicJarLoadingUsingSnappyJob.conf
dtests/src/test/java/io/snappydata/hydra/installJar/dynamicJarLoadingUsingSnappyJobsWithIdenticalNames.conf
dtests/src/test/java/io/snappydata/hydra/installJar/dynamicJarLoadingUsingSnappyShell.conf
dtests/src/test/java/io/snappydata/hydra/installJar/dynamicJarLoadingUsingSparkApp.conf
dtests/src/test/java/io/snappydata/hydra/installJar/installJar.bt
dtests/src/test/java/io/snappydata/hydra/installJar/verifyCleanupAfterSnappyJobExecution.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwReplicatedRowTablesTest.conf
dtests/src/test/scala/io/snappydata/hydra/InstallJarTest.scala
dtests/src/test/scala/io/snappydata/hydra/InstallJarTestSparkApp.scala

- Added test to verify that the classes loaded through install-jar command are not accessible to the spark App
- Added test to verify classes loaded through install-jar command are accessible to the snappy jobs and both the jobs works fine in parallel in spite of having same class name
- Added support in framework to specify the appName while running the snappy job.
- Added separate conf files for starting and stopping snappy embedded mode cluster
Verified the changes by running installJar.bt
NA
No

Additional test coverage for install jar feature

---

cluster/src/main/scala/org/apache/spark/executor/SnappyExecutor.scala

*  Fix for SNAP-1207
* This issue was intermitent which was caused when PutAllPRMessage was received by a member which has PartitionRegionPool but ThreadLocal was not set hence null check is safe here.
Tested by executing unit tests which was failing previously multiple times using a script
(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?) NA
(Does this change require changes in other projects- store, spark, spark-jobserver, aqp? Add the links of PR of the other subprojects that are related to this change) No

Fix for SNAP-1207

---

cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala

When a join result is joined with another table that is already partitioned on the join key, the exchange isn't avoided.  
The issue is with bucket linking we need to ensure that the  numBuckets of the two join children is same. But, when one join child is a join result of two tables, numBuckets is always 0 and hence the partitioning mismatch. 
Avoided the exchange by disabling setting of buckets for non delinking cases. 
Running pre-checkin.

[SNAP-1205]Avoid exchange when the table is partitioned with the join key

---

cluster/src/dunit/scala/org/apache/spark/sql/TPCHDUnitTest.scala
cluster/src/dunit/scala/org/apache/spark/sql/TPCHSuite.scala
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/RowTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/DelegateRDD.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/LocalJoin.scala

1. Updated LocalJoin to handle cover colocated join cases as well.
2. SnappyStrategies now convert a non-replicated table equi join into a local join if the plan.statistics.sizeInBytes < 100 MB. This default size can be altered using snappydata.localhashjoinsize SQLConf property.
3. Build side and stream side produce the code inside the doProduce of the LocalJoin. To supply the iterator of the rdd of build-side to the produce of build side, slightly hackish way has been used.
4. For colocated join, there is no need to cache the map.
5. Specified the clustering of local join so that the exchange nodes are introduced when needed.
6. Since the inputRdds of LocalJoin returns stream side rdd, the shuffle dependencies of the build rdd are never materialized during the query execution. This …

Updated LocalJoin to handle cover colocated join cases as well.

---

core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala

Currently if a hashmap can be build for the right side, it is marked as the build side without checking the size of the left side.
Checking the size of the left side before marking right as the build side.

Check the size of left side before deciding the build side 

---

cluster/src/dunit/scala/io/snappydata/cluster/DistributedIndexDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala

+ Now instead of creating ShuffleExchange explicitly, using
requiredChildDistribution to indicate shuffle is required at this
operator.
+ Adding IndexColumnFormatRelation too in avoiding 1 to many partition
to bucket mapping in other words avoiding delinking of partition ->
buckets.
tests: Added new dunit which will be enhanced to cover more conditions
as covered in unit test

Handling Exchange via EnsureRequirements

---

cluster/src/dunit/scala/org/apache/spark/sql/TPCHDUnitTest.scala
cluster/src/dunit/scala/org/apache/spark/sql/TPCHSuite.scala
cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/TPCH_Snappy.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnCacheBenchmark.scala
core/src/main/java/org/apache/spark/sql/execution/HashingUtil.java
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashSet.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/LocalJoin.scala

As seen in TPCH Q4 and others, building hash join map was taking a lot of time. The major contributors are:
1) Copying of UTF8String -- while this is okay for small maps, it causes a large overhead for larger ones
2) EXISTS(SELECT *) is not optimized by Spark so all columns of the table appear in projection and get populated in the map. Currently TPCH queries have been modified to use "SELECT 1" -- needs fix in Spark optimizer or addition to snappydata optimizer.
3) Multi-values array increments in steps of 1. Now using a 25% increment (with minimum as 4)
Apart from above, micro-benchmarked insert/get performance of a bunch of hash maps: Spark's OpenHashSet, Scala's HashSet, JDK's HashSet, FastUtil's ObjectOpenHashSet and compared to Snappy's implementation. The conclusion was that ours …

[SNAP-1225] Performance improvements for hash joins (and other fixes)

---

cluster/src/dunit/scala/org/apache/spark/sql/NorthWindDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/execution/DictionaryOptimizedMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala

NPE Fix:
+ The original query is no more using the same code generation logic
where NPE was getting hit but instead 'select distinct ShipCountry from
orders' was hitting it.
+ Handled null as suggested by Sumedh
+ Tested manually as it wasn't showing up in embed mode, will add a test
in SplitClusterDUnit covering this case.
+ refactored the NW schema a bit to reuse externally.
precheckin: No new failures.

Fixes NPE in select distinct query

---

core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/LocalJoin.scala

The reason for the issue was that the pre-evaluation of only required variables actually evaluated too much in some cases. The build side variables (i.e. results coming from the hash map of join) should never be pre-evaluated rather only the child streaming plan side variables should be. The difference in the generated code looks like below (for Q35 of NorthWindTest):
before (incorrect)
```java
/* 308 */           if (localjoin_entry == null) continue;
/* 309 */
/* 310 */           int localjoin_entryIndex = 0;
/* 311 */           int localjoin_numEntries = -1;
/* 312 */           Val_localjoin_LocalMap[] localjoin_values = null;
/* 313 */           // for first iteration, entry object itself has value fields
/* 314 */           Val_localjoin_LocalMap localjoin_value = localjoin_entry;
/* …
```

[SNAP-1245] Result mismatch due to variables not being re-evaluated in loop

---

cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
core/src/main/scala/io/snappydata/ToolsCallback.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/RowTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/datasources/StoreDataSourceStrategy.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/LocalJoin.scala

- LocalJoin now adjusts its requiredChildDistributions to match that of a child in case
partial set of join keys match the partitioning of one or both children
- check for subset match order to see if the same can be applied to both children,
else if both had different matches then choose the child with bigger size as per plan statististics
- also add join column aliases from projections, if any, to OrderlessHashPartitioning
TODO: add similar to SortMergeJoinExec (or its optimized version in SnappyData when it is added)
precheckin; TPCH Q2, Q5, Q9 plans, NorthWind test
NA
https://github.com/SnappyDataInc/spark/pull/37

[SNAP-1252][SNAP-1251] Avoid exchange when join columns are superset of partitioning

---

cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala
cluster/src/test/scala/io/snappydata/benchmark/memsql/TPCH_Memsql.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/TPCH_Snappy.scala
tests/benchmark/snappy/2_Setup.sh
tests/benchmark/snappy/7_generateResult.sh

--In Memsql,
Order table's clustered columnstore key is chnaged from O_CUSTKEY to O_ORDERKEY
LINEITEM table's clustered columnstore key is chnaged from O_CUSTKEY to O_ORDERKEY
Q4 and Q21 is changed where l_orderkey is projected instead of *
--In Snappy,
Small change at all places in queryExecution, where plan generation condition is added before collecting result
Q2,Q11,Q17,Q22 were broken in multiple parts. Now original queries are used
--Script
Instead of just copying out files, logs files will also be copied to output locations
While starting lead, locator, server no need to have classpath parameter.
Ran:
TPCH perf tests
(Does this change …

--TPCH Changes

---

cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardTab.scala

* Updating default URL redirection (within SnappyData code) to redirect user to Dashboard UI page.
* Tested Manually
* https://github.com/SnappyDataInc/spark/pull/42

SNAP-1281: UI does not show up if spark shell is run without snappydata

---

build.gradle
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/backwardcomp/logicalPlans.scala
core/src/main/scala/org/apache/spark/sql/backwardcomp/sparkPlans.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala
core/src/main/scala/org/apache/spark/sql/sources/StoreStrategy.scala
core/src/main/scala/org/apache/spark/sql/types/TypeUtilities.scala
core/src/test/scala/org/apache/spark/sql/store/SnappyCatalogSuite.scala

Snappy 0.7 should work with Spark versions >= 2.0.0 and versions < = 2.0.2 in connector mode. This PR fixes the issues related to that. 
- Changed the spark version for snappy-core to 2.0.0. 
- Copied three classes from Spark to Snappy as there is no compatibility between 2.0.0 and 2.0.2 versions of those classes. RunCommand, DescribeTableCommand, ExecutedCommandExec. 
- Added reflection to create JacksonGenerator object as its apply method has changed between two versions. 
- Added reflection to find out the parameter 'child' for CreateTableUsingAsSelect. 
Clean precheckin.

Fix Backward compatibility with 2.0.0 Spark

---

cluster/src/dunit/scala/org/apache/spark/sql/TPCHDUnitTest.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/TPCH.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/TPCH_Snappy.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpchmodifiers.scala
cluster/src/test/scala/org/apache/spark/sql/IndexTest.scala
core/build.gradle
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/sources/RuleUtils.scala
core/src/main/scala/org/apache/spark/sql/sources/SnappyOptimizations.scala
core/src/main/scala/org/apache/spark/sql/sources/subrules.scala
core/src/test/scala/io/snappydata/SnappyFunSuite.scala
core/src/test/scala/org/apache/spark/sql/store/CreateIndexTest.scala

Fixing the join order determination based on cost per our discussion instead of heuristics based.
Added a generic way to compare base TPCH (per spec) with/without snappy changes with/without index in consideration.
Using spark benchmark framework for comparison .
Compared with Snappy manual modified tpch queries and all are matching with results and plans show negligible impact.
Perf numbers generated using the checkedin set of csv data...
Table Sizes:
(lineitem,4884)
(nation,25)
(supplier,10000)
(customer,150000)
(orders,200000)
(region,5)
(part,200000)
(partsupp,200000)
```
JoinOrder optimization:                  Best/Avg Time(ms)    Rate(M/s)   Per Row(ns)   Relative
------------------------------------------------------------------------------------------------
q1 size 4884
q1 …
```

Avoid bcnl

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala

Changed the Snappy UI port from 4040 to 5050. This is done to avoid port clash when smart connector is run on the same machine.
Manual testing.

Spark UI Port 

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala

Fix for AQP-211. Removing the check of isSampleRegionReservoir while declaring weightage variable.

Fix for AQP-211

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/sources/MutableRelationProvider.scala

Removed the incorrect calls to unregisterDataSourceTables.
These calls are not required when the register of data source tables is done in the last.

[SNAP-1371]

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatchCreator.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCSourceAsStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowInsertExec.scala

Three issues were identified for the failure noted in SNAP-1372:
a) incorrect join result with inserts from connector when there is an exchange in the join (and not broadcast)
b) small 1-2 row column batches being created in smart connector mode
c) hydra test run shows the plan with exchange which is unexpected given the table sizes
- incorrect exchange join results when data is read from column store (works correctly when all data is from row buffer)
- issue was incoming partitionId being ignored in JDBCSourceAsColumnarStore.getPartitionID in smart connector mode
- also corrected it in base JDBCSourceAsStore (though will never be invoked in practise)
- small column batches (1-2 rows) being inserted into column store in smart connector mode
- now blow up the batch into row buffer even in …

[SNAP-1372] Fixing two issues identified when running NorthWind Q27

---

cluster/src/dunit/scala/org/apache/spark/sql/NorthWindDUnitTest.scala
cluster/src/dunit/scala/org/apache/spark/sql/SmartConnectorFunctions.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala

1. For NW tests, run the colocated table queries in smart connector mode and verify.
2. Reduce the logging level of job server's configuration parameter.
Ran the NW tests. Did manual testing for point 2. 
https://github.com/SnappyDataInc/spark-jobserver/pull/8

SmartConnector support in one NWtest

---

cluster/src/dunit/scala/org/apache/spark/memory/SnappyUnifiedMemoryManagerDUnitTest.scala
cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala

When Snappy executor is stopped it waits for 5 secs before closing the block managers. If driver starts another executor thread before the previous executor is stopped it shows many side errors.
While this is not a practical problem , this error may manifest in our tests. For now I have increased the restart time in test itself.
UMM tests

[SNAP-1437] NPE in SnappyUnifiedMemoryManagerDUnitTest

---

build.gradle
cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySharedState.scala
core/src/main/scala/org/apache/spark/sql/row/GemFireXDDialect.scala
core/src/main/scala/org/apache/spark/sql/sources/MutableRelationProvider.scala
core/src/main/scala/org/apache/spark/sql/sources/jdbcExtensions.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala
core/src/test/scala/org/apache/spark/streaming/SnappyStreamingContextSuite.scala

Addressing long standing issue of external/stream and other table types not showing up in the JDBC/ODBC meta-data.
- added executor-side query to SnappyHiveCatalog for non-store hive tables
- store schema for all cases in SnappyStoreHiveCatalog.registerDataSourceTable
- using just the name for ExternalTableType store/query and not toString()
- cleaning up and refacring code a bit to reduce duplication (e.g. getting schema
from hive Table object is now in ExternalStoreUtils)
precheckin in progress
NA
see store side PR for SNAP-303

[SNAP-303] Handle non-store hive tables in meta-data queries

---

cluster/src/test/scala/io/snappydata/QueryTest.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/DictionaryOptimizedMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/aggregate/SnappyHashAggregateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoinExec.scala

Failing query:
select sdk_version, count(distinct device_id) from (select sdk_version,
device_id from YES_WITH group by sdk_version, device_id) a group by sdk_version
(this fails only if the table YES_WITH is partitioned on device_id when EXCHANGE is avoided)
Fixes #534. The issue is due to hashjoin/aggregate referring to dictionary
variables that are not in its scope. Ideally the information about dictionary
variables should be transmitted through additional fields ExprCode() but
an extension to that does not work since Expression.genCode creates new
ExprCode objects without copying the incoming ones if possible
(in particular the simple BoundReference also ends up losing the
original extension class object)
So the code resorts to using context objects via SnappySession. The lookup
key …

[GITHUB-534] Match against variable name for dictionary optimization

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala

Modified ColumnInsertExec to handle wide schema to 1012 columns.
* Have separated out the methods handling wide schema so as not to impact performance of existing code and narrow schema
* Chunked the code to different methods to make java function size well withing 64K
pre-checkin yet to run
NA
NA

[SNAP-1384] : Column Table Inserts can fail if generated code is big

---

ReleaseNotes.txt
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala

- UI SQL Tab now displays SQL Query string instead of CachedDataFrame handler in Description column.
- Queries executed from Snappy shell and spark shell will be displayed as actual query string under Description column.
- Queries executed using API will display CachedDataFrame handler description as per previous behavior.
- SQL Tab on UI, Description column now displays actual SQL Query string executed instead of handler description text.
- None.

SNAP-1481 : Spark UI SQL tab needs to show the SQL query

---

cluster/src/dunit/scala/org/apache/spark/memory/SnappyUnifiedMemoryManagerDUnitTest.scala

Disaabling UMM tests for intermittent failures. 
These tests need to be enabled again, once the intermittent failures are resolved.
NA
NA
NA

Disaabling UMM tests for intermittent failures.

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/DictionaryEncoding.scala
dtests/src/test/scala/io/snappydata/hydra/SnappyTestUtils.scala

- Reused buffer size should be at least the minimum required else create new one
- Also use repartition(1) in test result collection instead of coalesce(1)
so that the scan is parallel. Reduces its running time by an order of magnitude.
hydra test mentioned in SNAP-1542 and precheckin
NA
NA

[SNAP-1542] Ensure that the size of buffer is at least the minimum required

---

cluster/src/dunit/scala/org/apache/spark/sql/ColumnBatchScanDUnitTest.scala
cluster/src/dunit/scala/org/apache/spark/sql/TPCHSuite.scala
cluster/src/main/scala/io/snappydata/cluster/ExecutorInitiator.scala
cluster/src/test/scala/io/snappydata/QueryTest.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala
core/src/test/scala/org/apache/spark/sql/execution/AggregationSuite.scala
core/src/test/scala/org/apache/spark/sql/store/CreateIndexTest.scala
core/src/test/scala/org/apache/spark/sql/store/UnifiedPartitionerTest.scala
dtests/src/test/java/io/snappydata/hydra/snapshotIsolation/columnTableExtn.inc

- skip DDL options in ExternalStoreUtils when creating the set of connection properties
- corrected remaining instances of column batch size settings in tests to mean byte size (instead of number of rows)
precheckin
NA
NA

[SNAP-1555] filter out the DDL options in connection properties

---

dtests/src/resources/scripts/northWind/nw_queries.sql
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/cluster/stopDualModeCluster.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwPartitionedRowTablesWithEvictionOverflowTest.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwPartitionedRowTablesWithEvictionTest.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwPersistentColocatedTablesTest.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwPersistentColumnTablesTest.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwPersistentPartitionedRowTablesTest.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwPersistentPartitionedRowTablesWithEvictionOverflowTest.conf
dtests/src/test/java/io/snappydata/hydra/northwind/nwPersistentReplicatedRowTablesTest.conf
dtests/src/test/java/io/snappydata/hydra/northwind/stopDualModeCluster.conf
dtests/src/test/scala/io/snappydata/hydra/northwind/NWQueries.scala
dtests/src/test/scala/io/snappydata/hydra/northwind/NWTestUtil.scala

- Modified the Q60 from northWind schema to work in snappy
- Added support to start the locator server and lead nodes with user specified launcher properties
- Added support for generating the executor logs in test directory (SPARK_WORKER_DIR set to testLogDir)
- Added support for providing the user specified paramerts for spark-submit
- Added support to use product defaults for lead, locator and server memory in case not provided by user
- Added support to collect heap dump on OutOfMemoryError in server and lead members
- Modified the test code to include the cluster stop and cleanup in ENDTASK to make sure that task will always get executed
- Minor code refactoring changes done
Verified the changes by running few tests from northWind.bt
NA
No

Framework enhancement for supporting number of user specified properties and parameters

---

core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala

CachedPlanHelperExec spark plan which has been introduced to facilitate Tokenization use to also show up in the dashboard UI. This is not useful to the user and so removing it from the dispaly by calling a simple transform.
Manual.
No.
None.

CachedPlanHelper is now removed from the plan information for UI.

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/clusterRestartWithPersistentRecovery.conf

- Added support in framework for calculating default executor memory for spark executors based on number of cores available on machine in order to avoid SNAP-1560
- Added support for using random port for spark master instead of 7077
- Fixed a minor test issue
Verified the changes by running few tests from northWind.bt
NA
No

Support in framework for calculating default executor memory for spark executors

---

cluster/src/dunit/scala/io/snappydata/cluster/DistributedIndexDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/cluster/ExecutionEngineArbiterDUnitTest.scala

Now replicated table queries also having multitable table joins, group by orderby distinct etc. will get routed to lead node.
Modofied test passes with the new code.
None.
None.

Test changes as per modified execution engine order rule.

---

core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/test/scala/org/apache/spark/sql/store/CreateIndexTest.scala

Unique index was not getting created on replicated table through snappy session
Fixed a small parser action issue to take care of this.
Added this case in an existing test.
None.
No.

Fix for SNAP-1385

---

cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala

"In Memory Size" could be just "Memory Size". Also "Total Size" is not enough for users to understand that this is memory and overflow size. Perhaps should put in brackets of title like "Total Size (Memory+Disk overflow)", or just "Memory and Disk overflow size"
Tested manually.

SNAP-1258: [Feedback from Sumedh]

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
core/src/main/scala/io/snappydata/util/ServiceUtils.scala

Requirement is to pass properties starting with  gemfire-grid.  to be passed to GemFireStore.
If the prefix is not done, it gets flitered in a function  ( because it is not belonging otherwise to store or snappy-spark).

Multigrid master

---

cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
cluster/src/test/scala/org/apache/spark/memory/SnappyStorageEvictorSuite.scala
core/src/main/scala/org/apache/spark/memory/StoreUnifiedManager.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala

When recovery was in progress it occupied almost all the off-heap memory available.
Also during recovery we use a temp UMM which has its limit set from defaults.
Also it can not do any eviction.But a side effect of exhausting all off-heap memory
in recovery is other messaging are not able to get any memory and restart hangs
Manual
NA
https://github.com/SnappyDataInc/snappy-store/pull/207

[SNAP-1664] LowMemoryException during cluster restart

---

core/src/main/scala/io/snappydata/SnappyThinConnectorTableStatsProvider.scala
core/src/main/scala/org/apache/spark/sql/SmartConnectorHelper.scala

Changes from @hbhanawat  and @sumwale.
Add client driver classname as a driver property when creating a connection factory. It avoids 'No suitable driver' issues when driver is not auto-loaded.
Manual testing with Apache Spark. 
./bin/spark-shell  --master local[*] --conf spark.snappydata.connection=localhost:1527 --jars /latest/master/snappydata-core.jar
NA
NA

(SNAP-1684) Add client driver classname as a driver property when creating a connection factory

---

cluster/src/dunit/scala/io/snappydata/cluster/DDLRoutingDUnitTest.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnCacheBenchmark.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/collection/MultiColumnOpenHashSet.scala
core/src/main/scala/org/apache/spark/sql/execution/CodegenSparkFallback.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/aggregate/SnappyHashAggregateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoinExec.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

- CodegenSparkFallback plan added at the very top to catch code generation failures and
fallback to Spark plans. This plan is completely transparent and delegates everything
to child (including "children" itself) so will never be visible in SparkPlanInfo or anywhere else.
- Switch the "disableStoreOptimizations" flag in its execute* overrides to fallback to Spark plans.
- Removed the old handling in SnappySession.load that only works for sql() API while
above works for all cases.
- Added testcase in ColumnCacheBenchmark
- Removed OFFHEAP option from StoreUtils which refers to Gem/GemXD option and is not supported.
- Some scalastyle corrections.
precheckin
NA
Some AQP changes

[SNAP-1710] separate plan to fallback to Spark

---

cluster/src/test/scala/io/snappydata/QueryTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatchCreator.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/datasources/StoreDataSourceStrategy.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowTableScan.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

- pass through "caseSensitive" flag to ColumnTableScan and RowTableScan to
do resolution as per case-sensitivity settings (in base PartitionedPhysicalPlan.fieldIndex);
the method uses a temporary LocalRelation to invoke resolveQuoted
- always use case-insensitive resolution for partitioned column resolution since
it may be case-insensitive during CREATE TABLE (and we are not storing that
flag in the DDL itself); this means that users can't have two columns
that just differ in case-sensitivity esp for partitioning which is a reasonable
restriction
- SnappyBaseParser now has caseSensitive flag as a var which is updated on each
top-level parse() call since the flag in SQLConf may have changed
- added a test in QueryTest as per the failure scenario mentioned in SNAP-1714
with different case …

[SNAP-1714] correcting case-sensitivity handling for API calls

---

cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnCacheBenchmark.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/DictionaryEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/Uncompressed.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEntry.scala

- now using a single common batch count column (first one) in the stats row removing
the separate count per column
- removed updateCount() from ColumnEncoders
- added test for normal and wide schema with this scenario in ColumnCacheBenchmark
precheckin
NA
NA

[SNAP-1735] use single batch count in stats row

---

core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/test/scala/org/apache/spark/sql/store/SnappyCatalogSuite.scala

SnappyCatalogSuite fails with following exception for "list tables" test
```
Failed to find data source: column. Please find packages at http://spark-packages.org
java.lang.ClassNotFoundException: Failed to find data source: column. Please find packages at http://spark-packages.org
at org.apache.spark.sql.execution.datasources.DataSource.lookupDataSource(DataSource.scala:145)
at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:78)
at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:78)
at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:310)
at org.apache.spark.sql.hive.SnappyStoreHiveCatalog$$anon$1.load(SnappyStoreHiveCatalog.scala:179)
at …
```

Fix for SNAP-1641

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
core/src/main/scala/io/snappydata/collection/ByteBufferHashMap.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatch.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/DictionaryEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEntry.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala

- ensure that the expanded bitset size is able to accomodate the incoming ordinal
- reduce byte copying and boxing for wide-table inserts:
- use SpecificMutableRow instead of GenericMutableRow to avoid primitive boxing
- use own setColumn method instead of CodegenContext.setColumn that avoids cloning
of UTF8String which is not really required
- refactored encoder close in ColumnInsertExec to use for wide-table case too
(else those remain dangling until collected by some GC cycle)
- use a maxDeltaRows for wide-schema case too in ColumnInsertExec
- use buffer.limit() instead of capacity in ByteBufferHashMap
- corrected some scalastyle/indentation
precheckin, failing test cases
NA
https://github.com/SnappyDataInc/spark/commit/5147b60ec4a627565a692dba59244bbd214cd3e4 reduces byte copying in …

[SNAP-1760] Correct null bitset expansion and reduce copying in inserts

---

examples/src/main/scala/org/apache/spark/examples/snappydata/WorkingWithObjects.scala

Code generation for SpecificSafeProjection fails for the above-mentioned example if one uses dataSet.collect() instead of dataSet.show()
The failure is due to type mismatch between immutable.map and scala.collection.Map.
Changed the example to use scala.collection.Map interface.
Manual testing
NA
NA

[SNAP-1721] Avoid code generation failure

---

cluster/src/dunit/scala/org/apache/spark/memory/SnappyUnifiedMemoryManagerDUnitTest.scala
cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
cluster/src/test/scala/org/apache/spark/memory/MemoryFunSuite.scala
cluster/src/test/scala/org/apache/spark/memory/SnappyMemoryAccountingSuite.scala
cluster/src/test/scala/org/apache/spark/memory/SnappyStorageEvictorSuite.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala

We have safeguarded the result serialization memory consumption from each partition. These safeguards are put in CachedDataFrame. Before copying the result iterator to heap we ask UMM for memory availability. If sufficient memory is not available the partition of result task fails. 
When accounting in UMM we take memory from the storage pool. This leads to code complexity and unused execution pool space. Also, it unnecessarily evicts some table data which otherwise could have fitted in memory
Use execution memory instead of storage memory for CachedDataFrame serialized memory.
For this, we create a memory consumer which acts on behalf of ResultTask and asks for execution memory. 
Also added a guard in execution pool to stop growing the pool beyond a storage fraction. 
Couple of test …

[SNAP-1688] Use execution memory for serialized result.

---

build.gradle
core/src/main/scala/io/snappydata/impl/ServerImpl.scala
core/src/main/scala/io/snappydata/util/ServiceUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala

- increasing the default member-timeout to 30s
- refactored methods a bit to do all SnappyData specific default boot setup in one place
- removed explicit pool minEvictableIdleTimeMillis added previously and let it be default
precheckin
Mention in best practices guide that default for member-timeout is 30s and needs to be increased further only if trouble is still seen.
NA

[SNAP-1777] increasing default member-timeout for SnappyData

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/cluster/ValidateMVCCDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/externalstore/ColumnTableDUnitTest.scala
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableInternalValidationTest.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala

* Changes from Sumedh @sumwale to create the CachedBatch tables inside user's schema
instead of in the earlier common schema named SNAPPYSYS_INTERNAL
* Fix the Catalog consistency part with the above changes.
Old PR https://github.com/SnappyDataInc/snappydata/pull/707
Clean precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/242
SnappyDataInc/snappy-aqp#153

SNAP-1808 Create cachedbatch tables in user's schema instead of SNAPPYSYS_INTERNAL

---

cluster/src/dunit/scala/io/snappydata/cluster/DDLRoutingDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/SmartConnectorHelper.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala
core/src/test/scala/org/apache/spark/sql/store/RowTableTest.scala

- SnappyParser changes to support ALTER TABLE ADD/DROP COLUMN DDLs
- Added alterTable APIs in SnappyContext
- Added trait AlterableRelation
- Smart connector - alter table execution handling
- Added DDL routing dunits for Alter table
- scalaTests for alter table column and row tables
clean precheckin, manual testing
Yes

SNAP-1326 ALTER TABLE Support

---

core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala

Added a task context listener to explicitly remove the obtained memory.
This will remove warning messages at executor level.
precheckin (Pending)
NA
NA

[SNAP-1798] Explicitly removed MemoryConcumer memory.

---

core/src/main/scala/org/apache/spark/sql/SnappySession.scala
examples/src/main/python/AirlineDataPythonApp.py

Removed the code to selectively invalidate cache for failed analysis query in connector mode.
As any Analysis exception is caught and re-parsed. While parsing some of the RunnableCommand gets executed again and results in some weird error. 
e.g. A path not found exception became table already exists, as the command was retried.
Regarding issue [SNAP-1806] the doc needs to change to show another python app CreateTable.py. The airline example is too much dependent on old quick start and assumptions. 
e.g. We can not drop airline table if we don't drop airline_sample. The user would get confused.
pre-checkin 
NA
NA

[SNAP-1806] Changed the exception handling in SnappyConnector mode.

---

core/src/main/scala/io/snappydata/SnappyThinConnectorTableStatsProvider.scala

Changed warning message logged on connector side when embedded cluster's lead is down (by SnappyThinConnectorTableStatsProvider). 
Also changed exception when lead is down from NoDataStoreAvailableException to NoMemberFoundException
The message that will be warning displayed is:-
```
17/07/25 16:43:36 WARN SnappyThinConnectorTableStatsProvider: Warning: unable to retrieve table stats from SnappyData cluster due to java.sql.SQLException: (SQLState=38000 Severity=20000) (Server=localhost/127.0.0.1[1528] Thread=pool-3-thread-1) The exception 'com.gemstone.gemfire.cache.execute.NoMemberFoundException: SnappyData Lead node is not available' was thrown while evaluating an expression.
```
The earlier message was:-
```
17/07/10 15:15:48 WARN SnappyThinConnectorTableStatsProvider: …
```

Changed warning message

---

core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala
core/src/main/scala/io/snappydata/SnappyThinConnectorTableStatsProvider.scala

- SnappyTableStatsProviderService service should be started only once.
Manually Tested
NA

SNAP-1268: Code changes to start SnappyTableStatsProviderService service only once.

---

core/src/main/scala/org/apache/spark/sql/execution/ConnectionPool.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

Now each pooled datasources is keyed against both table-name and user-name.
Also removed redundant connection to XD from JDBCAppendableRelation.scala
Manual testing of scenario. 
Dunit tests for security.
Precheckin pending.
No
No

Now each pooled datasources is keyed against both table-name and user-name

---

cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyMemberDetailsPage.scala

- Changes related to spark side code refactoring and clean up.
- Tested Manually
- None
https://github.com/SnappyDataInc/spark/pull/64

SNAP-1744: UI itself needs to consistently refer to itself as "SnappyData Pulse"

---

cluster/src/dunit/scala/io/snappydata/externalstore/ColumnTableDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/sources/StoreStrategy.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala

* Changes to add path to the options map in StoreStartegy 
* Added Unit test and executed it manually
* Precheckin in progress
NA
NA

[SNAP-1878] Proper handling of path option while creation of external table using API

---

core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala

* Add a testcase for SNAP-1876: Restart the cluster and verify grant/revoke permissions are retained.
precheckin pending
NA
https://github.com/SnappyDataInc/snappy-store/pull/264

SNAP-1876 Grant/revoke on column table may not work after restart

---

cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/TAQTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala

- Spark 2.1 Encoders only handle Array of primitives through ScalaReflection and not generic array like Array[DecimalType]
- Overridden createDataFrame in SnappySession to avoid the Encoders route, which fixes the problem for both embedded and split mode.
- Enabled complexTypeTest
precheckin 
None
https://github.com/SnappyDataInc/spark/pull/66

SNAP-1787 - Handling Array[Decimal] in both embedded and split mode

---

ReleaseNotes.txt
cluster/src/main/scala/io/snappydata/gemxd/SnappyDataVersion.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala

1. Display SnappyData build details along with version number on Pulse UI.
2. Shift SnappyData logo to right most side on top bar Keep Pulse on left side.
3. Create SnappyData and Pulse image in same font style.
4. Remove "SnappyData Application UI" text from UI
5. Increase Description column width and resized/reduced other columns widths in members list.
6. Move "Used / Total" text on next line or into tool tip for Heap and Off-Heap columns.
7. Used only status image to display Members Status in members list (Text Running or Stopped is shown in tool tip.
8. Displaying Members list sorted based on members type (All Data Servers followed by all Leads followed by all Locators).
- Tested Manully
Yes.
Spark: https://github.com/SnappyDataInc/spark/pull/69

Snap 1890 : Snappy Pulse UI suggestions for 1.0

---

cluster/src/test/scala/org/apache/spark/sql/SnappySQLQuerySuite.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala

The code to evaluate join condition is incorrect. Semijoin should traverse through all the values against a key which the code was doing.
However, the value field was not re-initialized afetr taking the next map entry against a key.
precheckin
NA
NA

[SNAP-1885] Semijoin incorrect result

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterMgrDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/test/scala/org/apache/spark/jdbc/ConnectionConfTest.scala
core/src/test/scala/org/apache/spark/sql/store/JDBCMutableRelationAPISuite.scala

* Removed mapping of custom built-in jdbc provider and instead use spark's JDBC provider
* Modified tests to use spark jdbc provider
* Precheckin
Needs some changes in documentation if we have documented it will do it with help of shyja
NA

[Snap 1871] Remove custom built-in jdbc provider and instead use spark's JDBC provider

---

cluster/src/main/scala/org/apache/spark/util/SnappyUtils.scala

As we have removed sc.addJar call, we need to add the driver jars to file server
at SnappyData level.
NA
NA
NA

After new job classloader changes executors not fetching driver files.

---

cluster/src/main/scala/org/apache/spark/executor/SnappyExecutor.scala
core/src/main/scala/org/apache/spark/sql/SmartConnectorHelper.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/TableExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatchCreator.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnDeleteExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowDeleteExec.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowInsertExec.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/hive/ConnectorCatalog.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala

- use "isPartitioned" flag to determined partitioned region instead of relying on numBuckets=1
- cleaned up SnappyParser a bit to use match-case; the real fix to SNAP-1919 is on AQP side
precheckin
NA
https://github.com/SnappyDataInc/snappy-aqp/pull/155

[SNAP-1919][SNAP-1916] added isPartitioned flag to determine partitioned tables

---

core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala

* Added a method similar to DataType.equalsIgnoreNullability but without comparing column names 
* This issue was caused due to improper comparision of complex datatype with that of base dataframe
* Added Unit test
* Precheckin in progress 
NA
No

[SNAP-1917] Fix for SNAP-1917 by proper comparing datatype of complex schema

---

core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala

CachedDataFrame.queryExecutionString was a function which is getting evaluated every time the CDF is being executed. Changed it to lazy val so that it is evaluated once. Same for the number of partitions of the cached RDD.  
precheckin

Issues seen during concurrency testing

---

core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala

The static initializer of Hive boots up with default properties i.e. derby causing
the issue reported in SNAP-1956. Setting hive metastore conf as system properties
avoids that and uses in-built snappy store as database instead. However, integer
value properties as system properties cause trouble so they are set later after
static initialization is done.
precheckin
NA
NA

[SNAP-1956] avoid derby booting in Hive's static initializer

---

core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/io/snappydata/SnappyThinConnectorTableStatsProvider.scala

- Switched to dbcp-builtin pool that honours maxWait to give up on connection get
after a timeout. Expectation is that dbcp-builtin will be in a better shape than upstream DBCP
pool which has been unmaintained for 7+ years
- Set datanucleus.connectionPool.maxWait to 30s
- Set the datanucleus.connectionPool.testSQL to VALUES(1) to force check a connection
(and re-create) when getting. This fixes the hang noted in SNAP-1972 jira with DBCP.
- Also set the hive scratch-dir to current working directory instead of default /tmp/hive
where user may not have write permission (some other user created and owns the directory).
It remains unused in any case.
- Close the SnappyThinConnectorTableStatsProvider connection in stop.
Addition of testSQL also sets the "testOnBorrow" property which means an …

[SNAP-1972] switch to dbcp-builtin pool with maxWait

---

cluster/src/dunit/scala/org/apache/spark/memory/SnappyUnifiedMemoryManagerDUnitTest.scala
cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala

Default spark memory fraction was 92% , after reserving memory for critical heap which is 10% default the total comes around 18% of reserved memory. This is a bit too much. We want to give a little buffer to JVM before it reaches the critical hep size. Hence increased default spark.memory.fraction to 97%
Also added couple of test changes. Enabled couple of tests which were failing frequently due to other problems. 
precheckin pending

[SNAP-1611]  made spark.memory.fraction to 97%

---

core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
dtests/src/test/java/io/snappydata/hydra/testDMLOps/SnappyDMLOpsUtil.java

The hive meta-store system properties are required to be set for static
initialization of Hive and should not be cleared because a concurrent
hive context initialization (from some other path) can see inconsistencies
like system property found but not available when actually read.
Also added file path location to file not found TestException message.
precheckin
NA
NA

[SNAP-1973][SNAP-1970] avoid clearing hive meta-store system properties

---

cluster/src/test/scala/org/apache/spark/sql/store/ColumnUpdateDeleteTest.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/BooleanBitSetEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeleteEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/DictionaryEncoding.scala

Issue is with merging of two deltas. While merging, we create a decoder and initialize it properties based on the decoders that are being merged. But encoder.initialize is not called and stringMap field of the DictionaryEncoder remains uninitialized and hence a null pointer exception. This code calls the initialize passing a minimum size.
Also allows "withHeader=false" for dictionary encoding 
Fix from @sumwale 
Enabled the test and precheckin.

Fix for SNAP-1985

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
cluster/src/test/scala/org/apache/spark/sql/store/ColumnUpdateDeleteTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/java/org/apache/spark/sql/hive/SnappySharedState.java
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnDeleteExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/BooleanBitSetEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnDelta.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowDeleteExec.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala
core/src/test/scala/io/snappydata/ColumnUpdateDeleteTests.scala
dtests/src/test/java/io/snappydata/hydra/testDMLOps/SnappyDMLOpsUtil.java

- update store link for the fix to SNAP-1989
- added unit tests for concurrenct updates/deletes
- use sync on a singleton object HiveClientUtil to fix SNAP-1986
- also fixed code generation issue with subExpressionElimination=true
that need InternalRow to be present (which is not created in
snappy plans) -- see Codegenerator.scala:765;
instead using wholestage subExpression elimination as done
in HashAggregateExec for update plans and removed from delete
plans which is not required since there are no update expressions
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/298

[SNAP-1989][SNAP-1986] merge concurrent column delta changes

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterMgrDUnitTest.scala
cluster/src/dunit/scala/org/apache/spark/memory/MemoryManagerRestartDUnitTest.scala
cluster/src/dunit/scala/org/apache/spark/memory/SnappyUnifiedMemoryManagerDUnitTest.scala
cluster/src/main/scala/io/snappydata/cluster/ExecutorInitiator.scala
cluster/src/main/scala/org/apache/spark/SparkCallbacks.scala
cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
core/src/main/scala/org/apache/spark/memory/StoreUnifiedManager.scala

There is a problem with the UMM when a executor goes down and comes up again. It will create a new UMM and its pools sizes will start from 0. The old state is not maintained. Also store reads SnappyUnifiedMemoryManager reference from MemoryManagerCallback which is a static field.
This means store & spark will account in two seprate UMM instance. 
To avoid that problem piggy backed on the temporary memory manager which is create when store boots up and Spark env is not ready. 
When executor goes down it will now call close() method of UMM. UMM will copy the old state to the temporary memory manager. When spark env is ready it will copy from temp manager as before.
Also, fixed one potential problem when multiple tasks fails for some reason, then executor sometimes restarts multiple times. …

[SNAP-1984] Code to copy UMM state.

---

core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
tests/common/src/main/resources/SparkSqlTestCode.txt

* Check for any exception in the output of running commands in spark-shell
* This was needed as some stack traces are shown on the spark console on rc1 branch which the test could have caught. Also, it also silently passed with some typos/bugs in the SparkSqlTestCode.txt
* Refactor testSparkShell() so that same code is re-used by SplitClusterDUnitSecurityTest
SplitClusterDUnitTest. precheckin NOT REQUIRED.
NA
NA

Check for any exception in the output of running commands in spark-shell

---

cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnCacheBenchmark.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/StringBenchmark.scala
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatch.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnDeleteExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeleteDecoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeleteEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaDecoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnDelta.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala

- check the bucket sizes to pick the least loaded bucket instead of picking a random one
- use global Random instead of class specific for better distribution with concurrent calls
(sync points not of much concern since its miniscule compared to overall batch creation/put)
- reduced the maximum number of rows per batch to 200k so that maximum skew will
be around that number in most cases
- added a "snappydata.linkPartitionsToBuckets" SQLConf property to disable de-linking
for all queries
- split out UTF8String tests into separate StringBenchmark from ColumnCacheBenchmark
With these changes, distribution in ColumnCacheBenchmark test, for example, is exactly equal
most of the time among the buckets. Other cases like those reported originally with 7M rows
have only ~50% difference between …

[SNAP-1993] fixes for data skew with no partition_by

---

core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala

* Fixed failure in testSparkShell() due to use of String.contains() instead of String.containsKey()
* Added tests for update/delete on column table with security enabled (currently fails with Jira 2004).
Failing unit tests. precheckin NOT REQUIRED.
NA
NA

* Fixed failure in testSparkShell

---

build.gradle
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
cluster/src/test/scala/io/snappydata/cluster/PreparedQueryRoutingSingleNodeSuite.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/StringBenchmark.scala
cluster/src/test/scala/org/apache/spark/unsafe/NativeUTF8StringPropertyCheckSuite.scala
core/build.gradle
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/catalyst/expressions/ParamLiteral.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala

- convert UTF8Strings in ParamLiteral to off-heap when snappy off-heap is enabled;
added DirectStringConsumer to acquire/release the required off-heap memory
- refactored the common code for TaskContext.get() into a separate method
which caches the result to avoid repeated thread-local lookups (Utils.genTaskContextFunction
should be used by snappydata code that needs it)
- SnappyParser changes:
- added a "likeExpression" method that will directly convert to StartsWith/EndsWith/Contains
expressions as per the like pattern with ParamLiteral so that off-heap conversion happens
for the pattern string (else Spark's LikeSimplification replaces with a Literal)
- enabled "inlineTable" rule which was commented out due to non-availabiity of
UnresolvedInlineTable plan in 2.0.1 (present since 2.0.2); …

[AQP-293] changes for JNI UTF8String.contains

---

cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
core/src/main/scala/org/apache/spark/memory/StoreUnifiedManager.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeleteEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnDelta.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEntry.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala

- free the buffer in a separate thread in background
- more precise data for eviction (with background it should not be too much eviction)
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/304

[SNAP-2007] fix deadlock between UMM and RegionEntry

---

cluster/src/main/scala/io/snappydata/gemxd/SnappySystemAdmin.java
cluster/src/main/scala/io/snappydata/tools/GfxdLauncherOverrides.scala
cluster/src/main/scala/io/snappydata/tools/SnappyUtilLauncher.scala

Hiding commands not applicable to snappy (will continued to be displayed for gfxd and rowstoremode)
Removed following commands:-
agent
modify-disk-store
export-disk-store
upgrade-disk-store
encrypt-password
shut-down-all
write-schema-to-xml
write-schema-to-sql 
write-data-to-xml
write-data-dtd-to-file
write-schema-to-db
write-data-to-db
replay-failed-dmls
SnappyUtilLauncher#getTypes uses SnappySystemAdmin (which uses help message modified for snappy "UTIL_Tools_DSProps" and "UTIL_Snappy_Tools_DSProps_HelpPost"). Earlier this was getting used only for "version" command.
Also hidden mcast related args from commands help (refer to store PR)
Also in SnappyData mode, error out if locators is not specified as an arg rather than using mcast port (refer to store PR). 
still to run precheckin
did …

Changes in the help displayed on snappy commandline

---

cluster/src/test/scala/io/snappydata/cluster/PreparedQueryRoutingSingleNodeSuite.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatch.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala

This is an intermediate fix for the issue. Changes for full fix were done but
became unfeasible to get those in due to new issues like SNAP-2007, SNAP-2012.
- skip stats if current batch has any updates in ColumnTableScan (very inefficient working fix)
- added a method "hasUpdatedColumns" to batch iterators for above
- uncommented checks in existing tests that were disabled due to SNAP-2004
precheckin with existing commented out checks enabled.
More comprehensive tests for this will be added with the full fix.
NA
NA

[SNAP-2004] skip stats check for updated batches

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala

With many concurrent inserts/partitions on a node, significant data skew in inserts
was still observed (on machines with large number of cores like 32) due to same
smallest bucket being chosen by multiple partitions.
This change now tracks the in-progress size for bucket and adds that to determine smallest bucket.
precheckin
NA
The atomic long field in BucketRegion to keep track of in-progress size was added in https://github.com/SnappyDataInc/snappy-store/commit/8410b4d30aa82a6a2af6dc2d2481d913dc4b60cc

[SNAP-2020] track in-progress insert size to avoid data skew

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala

Fix from @sumwale 
Called release for a buffer, which was causing the memory release by reference cleaner.
precheckin

[SNAP-2016] Released old decoder buffer.

---

cluster/sbin/snappy-start-all.sh
cluster/sbin/snappy-status-all.sh
cluster/sbin/snappy-stop-all.sh

[SNAP-2022] Remove the check which tested if any lead is already stopped, in snappy-stop-all.sh
* Add a check for rowstore, so that 'sbin/snappy-stop-all.sh rowstore' doesn't see the message.
* Add a while + case to handle option in any order.
Manual
NA
NA

[SNAP-2022] Remove the check which tested if any lead is already stopped, in snappy-stop-all.sh

---

core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

1. Order by and sort by clauses after partition by can be optional. It was
always expecting that.
2. INTERVAL non reserved key word was being treated as an identifier because
of optional clauses ordering.
Added a unit test.
None
No.

Fixed a couple of issues in parser.

---

cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala

Updated store for fixes to SNAP-2032
Also a change in TPCHColumnPartitionedTable to allow for text file
(and create parquet if specified) for supplier table even if it is configured
as column table (it can be configured as either a column table or row table)
precheckin, manual TPCH testing with bulk updates to ~50% rows
NA
https://github.com/SnappyDataInc/snappy-store/pull/316

[SNAP-2032] run old map GC task before throwing LME

---

cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala
core/src/main/scala/io/snappydata/ToolsCallback.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/CodegenSparkFallback.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/TableExec.scala
core/src/main/scala/org/apache/spark/sql/execution/aggregate/SnappyHashAggregateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnDeleteExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoinExec.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

The update/delete plans expect that input is ordered on batchIds in each
partition to minimize delta creation since they will end the previous
delta when a new batchId run-length is seen.
- instead of explicit check for Exchange in the plan to add sort on batchId
for above, use SparkPlan's outputOrdering and requiredChildOrdering for the
same which will be handled by EnsureRequirements automatically
- ColumnTableScan sends out ordering as that on batchId for update/delete case,
while those plans expect the child to be ordered on the same
- update the condition to introduce exchange; earlier it used to match
number of child partitions against target table buckets but that introduces
unnecessary exchange for bucket pruning; now carrying the table buckets in
OrderlessHashPartitioning and …

[SNAP-2033] use proper sort ordering for update/delete

---

cluster/src/test/resources/log4j.properties
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeleteEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaDecoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/UpdatedColumnDecoder.scala
core/src/test/resources/log4j.properties
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

- use the encoder nullWords array when reading from decoder on top of it in
final update delta creation
- moved null ordinal increment to notNull method to correct off by one error
(moveNext is one step ahead); renamed notNull method to readNotNull to indicate
that this increments cursor
- added test for null, not-null combinations
- updated cluster/core log4j.properties with latest defaults from store-log4j.properties
precheckin
NA
NA

[SNAP-2039] correct null updates to column tables

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala

- remove the override of running in LeadImpl which is no longer required
- update store link for the fix to SNAP-1960
precheckin with -Pstore
NA
https://github.com/SnappyDataInc/snappy-store/pull/326

[SNAP-1960] fix the RUNNING status being set prematurely

---

core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala

Global lock ensures no two hive client initializations end up trying  to
create the hive directory causing SNAP-1986
Removed the sync on initCommonHiveMetaStoreProperties and instead synchronize
on a common SnappyHiveCatalog.hiveClientSync for all hive client initializations
from SnappyHiveCatalog and HiveClientUtil.
precheckin
NA
NA

[SNAP-1986] use a global lock throughout hive client initialization

---

cluster/src/main/scala/org/apache/spark/ui/SnappyMemberDetailsPage.scala
core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/java/org/apache/spark/sql/hive/SnappySharedState.java
core/src/main/scala/org/apache/spark/sql/SmartConnectorHelper.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/aqp/SnappyContextFunctions.scala
core/src/main/scala/org/apache/spark/sql/catalyst/expressions/ParamLiteral.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/hive/ConnectorCatalog.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyExternalCatalog.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/sources/MutableRelationProvider.scala
core/src/main/scala/org/apache/spark/sql/sources/StoreStrategy.scala
core/src/main/scala/org/apache/spark/streaming/SnappyStreamingContext.scala
core/src/test/scala/io/snappydata/ColumnUpdateDeleteTests.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala
core/src/test/scala/org/apache/spark/sql/store/ViewTest.scala

This fixes two issues:
1. External connectors not working in smart connector mode as reported by Jags since the
required libraries may not be available in the embedded cluster. This happens because
the BaseRelation is attempted to be resolved in both "CREATE EXTERNAL TABLE" and
"DROP TABLE". Now resolve all required information (schema, inbuilt or not) at the
driver connector JVM and send that in the procedure calls for external providers.
2. Support for VIEW, VIEW...USING in the parser. Also cleaned up a few things in parser.
- fix external connectors in smart connector mode; resolve everything required
on the source connector and never try to resolve in embedded mode because it
may not have requisite libraries available
- added VIEW and VIEW...USING support to parser (createView, …

[SNAP-2072][SNAP-2073] fix external connectors; support VIEWs

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/build.gradle
core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/io/snappydata/impl/SparkConnectorRDDHelper.scala
core/src/main/scala/io/snappydata/util/ServiceUtils.scala
core/src/main/scala/org/apache/spark/serializer/PooledKryoSerializer.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/ConnectionPool.scala
core/src/main/scala/org/apache/spark/sql/execution/TableExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatch.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEncoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/hive/ConnectorCatalog.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/sources/MutableRelationProvider.scala
core/src/main/scala/org/apache/spark/sql/streaming/DirectKafkaStreamSource.scala
core/src/main/scala/org/apache/spark/sql/streaming/FileStreamSource.scala
core/src/main/scala/org/apache/spark/sql/streaming/KafkaStreamSource.scala
core/src/main/scala/org/apache/spark/sql/streaming/RabbitMQStreamSource.scala
core/src/main/scala/org/apache/spark/sql/streaming/RawSocketStreamSource.scala
core/src/main/scala/org/apache/spark/sql/streaming/SocketStreamSource.scala
core/src/main/scala/org/apache/spark/sql/streaming/StreamBaseRelation.scala
core/src/main/scala/org/apache/spark/sql/streaming/TextSocketStreamSource.scala
core/src/main/scala/org/apache/spark/sql/streaming/TwitterStreamSource.scala
dtests/src/test/java/io/snappydata/hydra/tpch/TPCHPerfComparerTest.java
dunit/src/main/java/io/snappydata/test/dunit/standalone/ProcessManager.java

- SparkConnectorRDDHelper.scala: changed the UNION ALL query to a much smaller
IN query that is now correctly converted to getAll on store-side (note the
use of "select *" rather than projection that still cannot be dealt by store)
- SparkConnectorRDDHelper.scala: added the optimized path for thrift connection/statement
to set properties on it rather than making procedure call round-trips;
- SparkConnectorRDDHelper.scala: also removed obsolete code used by old accessor/peer
smart connector; copied its code for "orphanBuckets" i.e. data nodes having no network server
- removed some unnecessary commit() calls since snapshot commit is explicitly invoked
- make bucket sizes consistent in embedded and smart connector; these now always
go into the table properties else the defaults can be …

Fix the case of remote pull from smart connector

---

core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/sources/MutableRelationProvider.scala
core/src/test/scala/org/apache/spark/sql/store/CreateIndexTest.scala

Fix case-sensitivity of columns in CREATE INDEX.
- quote column names when executing CREATE INDEX against snappy-store to ensure
case-sensitivity
- format names as per case-sensitivity settings for API calls
(parser calls already handle that)
- refactored to add SnappyStoreHiveCatalog.formatName for all case conversions
- cleaned up and correct case-sensitivity in filter pushdown
- now quote columns pushed down for row table indexes and update Filter accordingly
- also lookup with upper-case names (case-insensitive) and avoid quoting for that case;
need to do this way because case-sensitivity information has been lost in filter pushdown
(i.e. coming from parser names are properly cased, but from API they may not and depend
on session case-sensitivity setting)
precheckin
NA
NA

[GITHUB-900] CREATE INDEX: quote case-sensitive columns

---

cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/store/CodeGeneration.scala

- use "spark.sql.codegen.cacheSize" for caches in CodeGeneration too but scaled down
- use SparkEnv in SnappySession planCache which is cleaner instead of SparkContext instance
- avoid Tuple5 creates and boxing/unboxing in SnappyUnifiedMemoryManager seen in perf
precheckin
Document the "spark.sql.codegen.cacheSize" property
https://github.com/SnappyDataInc/spark/pull/87

[SNAP-2120] use "spark.sql.codegen.cacheSize" for Snappy caches

---

cluster/bin/snappy
cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
cluster/src/main/scala/io/snappydata/cluster/ExecutorInitiator.scala
cluster/src/main/scala/org/apache/spark/scheduler/cluster/SnappyCoarseGrainedSchedulerBackend.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

- changed toString() to instead use the new canonicalString() for InternalDistributedMember
so that it never changes on different nodes of the cluster
- changed two map lookups (contains+get) by a single get lookup in multiple places
- added optional "dataextractor"/"dataextractloader" options to snappy script to launch
the respective tools (only for rowstore mode or when using only row tables)
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/348

[SNAP-2122] use DistributedMember.canonicalString() in block maps

---

core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnDelta.scala
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala
examples/build.gradle
examples/quickstart/scripts/Quickstart.scala

- explicitly changed the DDL of row buffer regions to use the new delta diskstore
- update store link which gets the store changes for this including metastore regions
going into the datadictionary diskstore (when default-schema for a connection is
SNAPPY_HIVE_METASTORE)
precheckin
Can mention the separate diskstores used for metastore and delta regions. In particular
the datadictionary on locators now contains all the metadata.
https://github.com/SnappyDataInc/snappy-store/pull/349

[SNAP-2121] mark delta regions to use the delta diskstore

---

core/src/main/scala/org/apache/spark/memory/DefaultMemoryManager.scala
core/src/main/scala/org/apache/spark/memory/StoreUnifiedManager.scala

We keep a map of memory used against each region. When we drop the region we release the total memory accumulated. This is not supported in DefaultMemoryManager( which gets used in local & connector mode). Hence the problem.
While acquiring memory for table it uses Spark's UMM , but does not release that memory when the table gets dropped.
manual test. Pre-checkin pending
NA
NA

[SNAP-2084] Handled dropStorageMemoryForObject in DefaultMemoryManager.

---

cluster/src/dunit/scala/io/snappydata/cluster/DDLRoutingDUnitTest.scala
core/src/main/scala/io/snappydata/impl/SparkConnectorRDDHelper.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala

Follow up PR for SNAP-2121 as per review comments
- if a disk-store has been defined for a column table, then use the corresponding
delta disk-store instead of a global one
- update store link for the store layer changes
precheckin
Note the new implicit delta disk stores in the docs.
https://github.com/SnappyDataInc/snappy-store/pull/350

[SNAP-2127] use separate delta disk-stores for row buffer regions

---

README.md

Changed download link from pointing at the releases page to pointing at our download page.

Fixed links in readme.md

---

core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala

* OVERFLOW=false disables eviction if EVICTION_BY is absent.
* Updated test cases.
unit tests.
precheckin running
A note about OVERFLOW option is deprecated.
NA

[SNAP-1501] OVERFLOW=false disables eviction if EVICTION_BY is absent.

---

cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/MapTest.scala
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala
core/src/main/scala/org/apache/spark/sql/sources/SnappyOptimizations.scala
core/src/main/scala/org/apache/spark/sql/sources/subrules.scala

Some parser performance improvements to recover the regression over 0.9 release.
Also optimized and enhanced numeric/decimal literal handling.
- moved paramLiteral/literal rule below the identifier one in primary; this was changed as part
of parser fixes to avoid treating INTERVAL literal as identifier (d015588) but cause perf trouble due to:
- rejecting identifier rule in case of mismatch is fast most of the time since it has to only
check against [a-z_] pattern which is done using a bitset check but rejecting literals
requires running through many rules that are ORed and parser has to check and
reject each one of those
- moreover, if tokenization is enabled then the rule has to do double the work of
first rejecting paramLiteral and then rejecting literal in non-match cases
- identifiers …

Parser performance improvements

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/externalstore/ColumnTableDUnitTest.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
cluster/src/test/scala/io/snappydata/QueryTest.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnCacheBenchmark.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatch.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/BitSet.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaDecoder.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/UpdatedColumnDecoder.scala
core/src/main/scala/org/apache/spark/sql/execution/row/ResultSetDecoder.scala
core/src/main/scala/org/apache/spark/sql/execution/row/UnsafeRowDecoder.scala
core/src/test/scala/io/snappydata/gemxd/BasicStoreSuite.scala

Brief overview of null handling in generated code and the new approach.
The initial code for null handling in ColumnTableScan was simple one where there was always
sequential iteration over all the rows for all the projected columns. The generated code
maintained current cursor position of decoder that indicated the position of current non-null
value to be read while nullability check was done with a separate call to decoder.
This changed completely with #793 (SNAP-1936) that changed sequential cursors to random
ones to handle cases of high filtering where cursors of other columns (having no filter
conditions but being projected) need not be updated anymore for every row. It complicated
the nullability handling because now the code needs to determine "number of nulls till this
point" to …

[SNAP-2088] fixes for queries with filters on columns with nulls

---

cluster/src/test/scala/io/snappydata/QueryTest.scala
cluster/src/test/scala/org/apache/spark/sql/SnappySQLQuerySuite.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnCacheBenchmark.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/TAQTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/test/scala/io/snappydata/SnappyFunSuite.scala
core/src/test/scala/org/apache/spark/sql/execution/AggregationSuite.scala
core/src/test/scala/org/apache/spark/sql/store/CreateIndexTest.scala

- SnappyParser.lateralView rule added used in relations rule
- added test using sample data/query mentioned on Slack by @Steve Felsheim
- moved common "checkAnswer" code to base SnappyFunSuite
precheckin
Support for LATERAL VIEW to be mentioned in docs.
NA

[SNAP-1283] LATERAL VIEW support in SnappyParser

---

dtests/src/test/scala/io/snappydata/hydra/ct/CTTestUtil.scala

The tests in regression failed to create tables in row store syntax using snappy cluster. As this is not supported, changed the tests to use snappy syntax for create table ddls.
Ran ct.bt
N/A
N/A

Changed the create table ddls to use snappy syntax instead of rowstore syntax

---

cluster/src/test/scala/io/snappydata/benchmark/snappy/TPCHPerfComparer.java
dtests/src/test/java/io/snappydata/hydra/smoke.sh
dtests/src/test/java/io/snappydata/hydra/tpch/TPCHPerfComparerTest.java
dtests/src/test/scala/io/snappydata/hydra/SnappyHydraRunner.scala

- Make the name of the file more readable
-smokePerf.bt will run as a part of smoke tests
-Commented out certain exceptions so that exceptions in smoke tests will be visible during precheckin (provided by Swati)
Ran:
smoke.sh

smokePerf related changes

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
cluster/src/main/scala/org/apache/spark/scheduler/cluster/SnappyEmbeddedModeClusterManager.scala
cluster/src/test/scala/org/apache/spark/sql/store/ColumnUpdateDeleteTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/scala/io/snappydata/impl/SparkConnectorRDDHelper.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/RemoteEntriesIterator.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala
core/src/test/java/io/snappydata/TestClass.java
core/src/test/scala/io/snappydata/ColumnUpdateDeleteTests.scala

- added "delayRollover" flag to scan RDDs and SnapshotConnectionListener in updates
to disable rollover during operation and do it explicitly, if required, just before commit
- flag is passed through two routes:
- ColumnUpdateExec overrides delayRollover which is passed to SnapshotConnectionListener;
this is the case where update starts its own transaction due to intermediate shuffle
- flag passed to row/column scan RDDs during construction (via Relation instance) which
is the case where there is no shuffle and scan started transaction is used
though issue is only for second case above, still delayRollover has been added to both
- added testOnBorrow flag to tomcat pool (hikari has it by default) to clean failed connections
- use empty string TXId for no TX instead of "null" string
- …

[SNAP-2192] delay rollover in column updates to pre-commit

---

cluster/src/test/scala/io/snappydata/benchmark/snappy/TPCDSSuite.scala
dtests/src/test/java/io/snappydata/hydra/startUp/nwTestWithAllServerHA_meanKill_clusterRestartWithRandomOrderForServerStartUp.conf

- Fixed the data and checkout path issue
- Disabling TPCDSSuite test run from precheckin as it takes around 2 hrs. Planning to add TPCDS tests to be run as a part of smokePerf bt which will run on a dedicated machine.
- Disabling the validation in TPCDSSuite for now as this requires the expected result files to be created using stock spark beforehand
- Modified test description in startUp test.
Verified the changes by running TPCDSSuite.scala
NA
No

Fix issues and disable TPCDSSuite from precheckin

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerTestBase.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/test/scala/org/apache/spark/sql/store/ViewTest.scala

Search the plan expressions to find any matching view aliases to determine the
underlying column for a join key. A physical plan for a query on join VIEW looks like:
```
Join Inner, (gen_attr_0#347 = gen_attr_2#349)
:- Project [ID#204 AS gen_attr_0#347]
:  +- Filter isnotnull(ID#204)
:     +- Relation[ID#204,ADDR#205] ColumnFormatRelation[APP.VIEWCOLTABLE]
+- Project [ID#248 AS gen_attr_2#349, ADDR#249 AS gen_attr_1#350]
+- Filter isnotnull(ID#248)
+- Relation[ID#248,ADDR#249] RowFormatRelation[APP.VIEWROWTABLE]
```
The underlying column is buried inside the Project alias while the join condition
is on generated attributes (gen_attr_0 and gen_attr_2).
Also changes to avoid multiple unapplies of ExtractEquiJoinKeys, PhysicalOperation rather
do it once and then match on the extracted …

[SNAP-2204] search through aliases (e.g. for VIEWs) for colocated join keys

---

core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoinExec.scala

Issue is due to the extra check condition in join being evaluated only once
for a key on build side which may be incorrect if the key has multiple values in the map
(similar to SNAP-1885 but for anti-join)
- pass the code for check condition separately to all join types and evaluate it inside
the loop over all values for a key
- also optimized the input evaluation for check condition to avoid evaluating
all the input (that will unnecessarily read all columns of a table, for example) rather
evaluate only the condition's Expresion references
- changed the fix in SNAP-1885 to move back inputCodes (which is stream-side columns that
won't change) outside the loop while only the separated out checkCode is re-evaluated
NA
NA
NA

[SNAP-2212] re-evaluate check condition for all values of a key in joins

---

cluster/src/test/scala/org/apache/spark/sql/SnappySQLQuerySuite.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/aggregate/SnappyHashAggregateExec.scala
core/src/test/scala/org/apache/spark/sql/store/RowTableTest.scala

For the case of dictionary optimized aggregate, the grouping key is not materialized rather
only the dictionary index is made use of (except for first insert in map for a key where
the full key is looked up separately). This caused trouble for the case when one of the
aggregate expressions uses the grouping key e.g. select id, count(id) from table group by id
because the key code would not be materialized.
It caused the compilation of snappy aggregate plan to fail which would fallback to spark
aggregation correctly. For some reason the fallback plan would sometimes fail with
a ClassCastException.
This change does not address the ClassCastException itself rather only fixes the snappydata
hash aggregation plan so that fallback spark plan is not used. Former may need to be tracked
separately …

[AQP-292] evaluate grouping keys explicitly if aggregates are using them

---

launcher/src/main/java/io/snappydata/tools/QuickLauncher.java

- the options map is in the form "key"->"-key=value" so split "value" from the map value
- pass boolean host-data separately as per store changes
precheckin, manual
NA
https://github.com/SnappyDataInc/snappy-store/pull/368

[SNAP-2215] split out argument value for log-file

---

cluster/src/dunit/scala/io/snappydata/cluster/SnappyTableStatsProviderDUnitTest.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyStatsPage.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala
core/src/main/scala/io/snappydata/SnappyThinConnectorTableStatsProvider.scala
core/src/main/scala/io/snappydata/TableStatsProviderService.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala

- use the new VTI to query for stats from smart connector instead of procedure
with serialized blob; also added sync blocks to correct thread-unsafe paths and
recreate the statement in case of any exception due to node failures or otherwise
- also corrected thread-unsafe mutable maps that are value of member info map;
changed to use java CHM consistently
- changed explicit thread creation in getMembersStatsOnDemand with a Future
which is both cleaner and does not require starting thread every time
- the new VTI calls will force the stats to be updated else thin stats service can
fall 2 times behind (due to delay in both that service and embedded service runs)
- removed obsolete and unused ExternalClusterMode (SNAP-1837)
- replaced two start methods in TableStatsProviderService with a …

[SNAP-2217] fix thread-unsafe paths in stats service and other cleanups

---

core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/catalyst/expressions/ParamLiteral.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala

Fixes the issue of incomplete plan info in UI due to plan caching changes.
This also addresses SNAP-1931 and SNAP-1906
Chose an inexpensive way of substituting just the current value in the ParamLiteral nodes in the plan and overriding the toString() method to use the currentValue instead of the constant value field.
Expensive transformation has been avoided for every run. Instead used once per cacheddataframe to just collect all the paralliteral nodes. The Spark metrics get properly reflected. Previously due to transformstion these fields were getting null and hence the problem. 
Manual testing
None.
No.

Fix for SNAP-1931, SNAP-1932 and SNAP-1906

---

core/src/main/scala/org/apache/spark/sql/execution/SecurityUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatch.scala

Make sure that connection is closed when task completes so that
tx is also committed.
Problem with closing connection early was that, same embedded connection can be used for other task which will use txState associated with previous task.
We make sure that conn is not closed until tx is also committed. All this is done till the end of task.
Ran precheckin and hydra tests.

Don't close connection early

---

cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/io/snappydata/util/ServiceUtils.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala

Precheckin tests fail as once a secured system is created in a test, it is not possible to shutdown the system using sparkContext.stop as creds are not passed.
Change is to retrieve creds from globalSparkContext ( assuming this is the context created during boot) & passing it to Utils for shutdown.
This fixes the failure of BugTest when run in the suite.

taking creds from globalSparkContext to shutdown the store

---

cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpch/SparkApp.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpch/SparkAppUsingJob.scala

Small fix in io.snappydata.benchmark.snappy.tpch.TableCreationJob to be able to correctly populate output of TPC dbgen in Snappydata using the correct scale factor.
TODO: The class needs further refactoring. There is plenty of duplicated code.
Ran TPC-H locally to verify data generation completes successfully

Fix for SNAP-2365

---

cluster/src/test/scala/org/apache/spark/sql/execution/DataGenerator.scala
cluster/src/test/scala/org/apache/spark/sql/execution/SnappyTableMutableAPISuite.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnUpdateExec.scala
core/src/main/scala/org/apache/spark/sql/store/CompressionCodecId.scala

Even if delta stats rows are not compressed ColumnFormatValue considered it as a compressed value and tries to decompress.
Stats rows are written as UnsafeRow. Unsafe row irrespective of nullability keeps nullbits.
So if 100 columns are  there stats row will contain 100 * 3 and UnsafeRow will contain
300 nullbits plus bits required for 8 bytes word allignment. Hence setting unused columns
as null does not really saves much.
These nullbits are set based on platform endianness. SD ColumnFormatValue
assumes LITTLE_ENDIAN bytes. However, Unsafe row itself does not force any endianness
and picks up from the platform. Hence a lower byte of the bit set  can be represented as
[11111110]. The 0th bit is for batch count which can never be null.
This causes SD ColumnFormatValue to understand stats …

[SNAP-2348] Invalid decompress call on stats row.

---

dtests/src/test/scala/io/snappydata/hydra/SnappyHydraRunner.scala
dtests/src/test/scala/io/snappydata/hydra/SnappyHydraTestRunner.scala

- Skip searching exceptions from hoststats files in smoke bt
Verified the change by running smoke bt after creating a connectionException.txt file and kept it open in vi editor during the test run.
NA
None

- Skip searching exceptions from hoststats files in smoke bt

---

core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/SnappySqlParser.scala

Code generation exception is not leading to fallback to Spark plan. 
This is because of presence of view which leads to a parse call from within Catalog.lookupRelation and clears the SnappySession context objects (so ExecutionKey required to retry is not found by CodegenSparkFallback).
This is to fix the spark fall back plan if code gen fails for SnappyData.
precheckin 
The actual fix for query failure on complex view will be with SNAP-2346

[SNAP-2363] Query on view fails.

---

cluster/src/test/scala/org/apache/spark/sql/execution/DataGenerator.scala
core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEntry.scala

a) While determining the off heap size of a PR the iterator only considered primary buckets.
Changed it to iterate over secondary buckets as well. 
b) Also added a utility method in DataGenerator to generate unique values based on a range.
Some formatting changes.
Manual testing. Pre checkin pending. 
NA
NA

[SNAP-2186] Fixed offheap size for PR

---

core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala
core/src/main/scala/org/apache/spark/sql/sources/StoreStrategy.scala

if deployed jars/coordinates not present during restart do not stop lead from coming up. Start and spit out warnings in logs.
Manual
None
No

Change to let 'lead' with warnings

---

cluster/src/test/scala/org/apache/spark/sql/execution/SnappyTableMutableAPISuite.scala

Adding ScalaTest for SNAP-2369 in snappy-cluster tests.

Adding ScalaTest for SNAP-2369

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala
core/src/main/scala/org/apache/spark/sql/streaming/StreamBaseRelation.scala

There was a small window when the connection is lost to the JDBC source JDBCMutable relation might drop the table, thinking of a failed initialization. 
pre-checkin
NA
Na

[SNAP-2347] Fix for row tables getting dropped.

---

cluster/src/main/scala/org/apache/spark/status/api/v1/TableDetails.scala
core/src/main/scala/io/snappydata/TableStatsProviderService.scala

- Fetching table stats and external table stats from objects populated by SnappyTableStatsProviderService instead of calling getAggregatedStatsOnDemand of SnappyTableStatsProviderService.
- Adding getAllTableStatsFromService and getAllExternalTableStatsFromService methods to fetch table stats and external stats.
- Tested manually and with the help of BT test
- None
- Spark: https://github.com/SnappyDataInc/spark/pull/108

Fixes for SNAP-2071 and SNAP-2400 :

---

cluster/src/main/scala/org/apache/spark/memory/SnappyUnifiedMemoryManager.scala

If boot time UMM cannot find any memory, its best to return from that place. This means the system itself is configured with very low memory, which is not capable of handling overhead for keys & region structures. 
precheckin
NA

[SNAP-2399] Added a check for boot time manager.

---

cluster/src/main/scala/org/apache/spark/sql/SnappySessionFactory.scala

Added StreamingQuery.stop on job server session.stop() method call. This will be called from JobManagerActor's JobKill.
precheckin
https://github.com/SnappyDataInc/spark-jobserver/pull/19

[SNAP-2306] Streaming query stop

---

cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala

- HTML code changes for displaying error message if loading Google charts library fails.
- Manual
- None
- Spark: https://github.com/SnappyDataInc/spark/pull/112

Fixes for SNAP-2422:

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala

Test is based on the hydra test mentioned in https://jira.snappydata.io/browse/SNAP-2247 in which it reproduced.
NA
NA
https://github.com/SnappyDataInc/spark/pull/114

Added a test for SNAP-2247

---

cluster/src/test/scala/org/apache/spark/sql/MiscTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala

select test.* from test -- works
but
select app.test.* throws exception - in snappy
Minor fix in parser to handle the above syntax too.
Unit test added.
No.
None.

Fix for SNAP-2434 in parser

---

core/src/main/scala/io/snappydata/impl/SmartConnectorRDDHelper.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala

In SmartConnectorColumnRDD#compute, moved the code to attach task completion listener into a finally block. This is because when call to helper.prepareScan throws an exception, the listener was not getting attached and therefore snapshotTxIdForRead was never set to null even after the task is complete. This resulted in invalid (old) txId getting used in subsequent tasks.
Ran the mentioned hydra test in bug 10 times. 
Ran SplitCluster* dunit tests
Precheckin to be run

Ent-29 Make sure that snapshotTxIdForRead is reset properly

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala

Security code used to set snappy username in all pool connection obtained in the system.
Added a check to allow it only for snappy.
precheckin
NA
NA

[ENT-34] Avoid setting snappy user name.

---

core/src/main/scala/org/apache/spark/sql/SnappyParser.scala

In "fetch first n row only" it was expecting to pass 'n' number of first rows.
Now we made n as a optional field, if n didn't pass then it will fetch first 1 row.

Added Fix to query with optional n argument

---

cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
core/src/main/java/org/apache/spark/sql/hive/SnappySharedState.java

Issue: SnappyData Dashboard and SQL tabs are visible even if Cluster is started with authentication enabled. Changes proposed to fix this issue are as follows.
- Set security handlers to all ServletContextHandlers which are created as a part of Dashboard, SQL tabs and Auto-refresh feature web services.
- Moved SQL tab creation from _SnappySharedState:createListenerAndUI_ to _ToolsCallbackImpl:updateUI_.
- Tested Manually with/without Authentication (LDAP)
- NA
Spark: https://github.com/SnappyDataInc/spark/pull/118

Code changes for ENT-21:

---

core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

**Problem:** Same member node is listed twice, in the UI, with different status.
**Cause:** Multiple Disk Store UUIDs are found when same member is shuts down and comes back again. 
Also if Disk Store is not found, then members stats are first stored against its Id as key in stats map. Later after Disk store UUID is available the another entry with Disk store UUID is added for same node.
**Solution:**
- Storing cluster members stats in map against their DiskStoreUUID(as key) only
and removing members ID as key.
- Tested using Cluster Recovery BT.
- NA
Store: https://github.com/SnappyDataInc/snappy-store/pull/415

Fixes for SNAP-2433:

---

core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala

[SNAP-2477] Adding an API to get table type for SnappyData tables.

---

cluster/sbin/snappy-encrypt-password.sh
cluster/sbin/snappy-leads.sh
cluster/sbin/snappy-locators.sh
cluster/sbin/snappy-nodes.sh
cluster/sbin/snappy-servers.sh

Added a new script snappy-encrypt-password.sh that accepts userIds, plaint text passwords and returns an encrypted passwords.
This scripts uses newly added proc SYS.ENCRYPT_PASSWORD(). This script starts a locator using user's conf file settings AuthProvider as none. The encryption key is stored in data dictionary.
Changes to other scripts to allow passing of command line args.
Changes done along with Sumedh.
Manual tests
Security dunit tests
Doc note to be added
Store side PR: https://github.com/SnappyDataInc/snappy-store/pull/419

Added a new script snappy-encrypt-password.sh

---

cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
cluster/src/main/scala/org/apache/spark/scheduler/cluster/SnappyCoarseGrainedSchedulerBackend.scala
cluster/src/test/scala/org/apache/spark/sql/policy/SecurityEnabledJdbcClientPolicyTest.scala
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala

- added snappydata.sql.disableHashJoin to disable all hash joins including
for replicated tables; the entire HashJoinStrategies is skipped with this as true
- use a boolean "disableHashJoin" in session to speed up lookup
- clear existing plan cache in case this flag is set
- clean up to remove scalastyle warnings in a bunch of classes
manual
Document the new property.
https://github.com/SnappyDataInc/snappy-store/pull/422

Property to disable all hash joins

---

cluster/sbin/snappy-encrypt-password.sh
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLPrepareImpl.scala
cluster/src/test/scala/org/apache/spark/sql/policy/AlterTableRowLevelSecurityEnableTest.scala
cluster/src/test/scala/org/apache/spark/sql/policy/PolicyJdbcClientTest.scala
cluster/src/test/scala/org/apache/spark/sql/policy/PolicyTest.scala
cluster/src/test/scala/org/apache/spark/sql/policy/PolicyTestBase.scala
cluster/src/test/scala/org/apache/spark/sql/policy/RestrictTableCreationPolicyTest.scala
cluster/src/test/scala/org/apache/spark/sql/policy/SecurityEnabledJdbcClientPolicyTest.scala
cluster/src/test/scala/org/apache/spark/sql/policy/SecurityEnabledPolicyTest.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/test/scala/io/snappydata/SnappyFunSuite.scala
examples/src/test/scala/io/snappydata/quickstart/ExampleTestSuite.scala

* disallow CREATE POLICY without security and enable-rls enabled
* link to store that disables smart connector and route-query=false client
connections with enable-rls disabled
* test changes to use a base PolicyTestBase that enables RLS and a flag
to allow RLS tests without security enabled
* other minor changes to fix occasional failures in ExampleTestSuite
precheckin in progress
document that RLS is not allowed with route-query=false
https://github.com/SnappyDataInc/snappy-store/pull/424

disallow row-level security only if "enable-rls" is set

---

core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/java/io/snappydata/impl/SnappyHiveConf.java
core/src/main/scala/io/snappydata/util/ServiceUtils.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala

These changes are to avoid interference in internal hive meta-store used by SnappyData from any
external hive meta-store configuration.
- adding a new "SnappyHiveConf" that extends HiveConf to clear all non-default configuration
(via reflection for few items) from the internal hive meta-store client
- preserve log-level from initialized SparkContext when booting store in local mode
if not set explicitly at store level (using "snappydata.store.log-level" property)
- correct scalastyle warnings/errors in some files
precheckin; manual testing with external hive meta-store using SparkSession
NA
NA

[SNAP-2555] clear non-default configs for internal hive meta-store client

---

cluster/src/test/scala/io/snappydata/benchmark/TPCH_Queries.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpch/QueryExecutionJdbc.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpch/QueryExecutionJob.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpch/QueryExecutor.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpch/SparkApp.scala
cluster/src/test/scala/io/snappydata/benchmark/snappy/tpch/SparkAppUsingJob.scala
tests/benchmark/snappy/dynamic/5_Jdbc_executeQuery.sh
tests/benchmark/snappy/dynamic/5_executeQuery.sh
tests/benchmark/snappy/dynamic/PerfRun.conf.template
tests/benchmark/spark/3_load_data__run_queries.sh
tests/benchmark/spark/PerfRun.conf.template

SNAP-2447: Set seed of random number used in query parameterization for reproducibility
Pass an additional parameter randomSeed in PerfRun.conf for TPC-H . Initialize a random number in TPCH_Queries with this seed for repeatable experiments (with exact same parameter values). 
Ran TPCHDUnit and ran the query execution job with the same seed locally to verify that query parameters are identical in these two runs. 
None

SNAP-2447: Set seed of random number used in query parameterization 

---

cluster/src/main/scala/io/snappydata/tools/SnappyUtilLauncher.scala

SnappyData specific GfxdDataSerializable types were not getting registered
when validate tool was getting launched through SnapyUtilLauncher.
This is because the StoreCallback was not getting initialized.
Initializing the store callback with the launcher fixed the issue.
Manual
No.
No.

Fix to disk store validate tool

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerLDAPTestBase.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
cluster/src/main/scala/org/apache/spark/scheduler/cluster/SnappyCoarseGrainedSchedulerBackend.scala
cluster/src/main/scala/org/apache/spark/scheduler/cluster/SnappyEmbeddedModeClusterManager.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyBasicAuthenticator.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java

These set of changes (along with those in store-side PR) allow one to specify server-auth-provider=NONE so that gemfire-level p2p authentication is disabled while the auth-provider will set the connection-level authentication (both for client connections and internal connections).
- allow for NONE as a valid security policy in Lead boot
- fixed and cleaned up lead property handling to set the properties correctly for start and stop
- updated calls from snappy layer to use the authentication service from the Database module
rather than the static version (which has not been removed on the store side)
- wait for sampler to fully initialiaze before proceeding with hive catalog initialization
- changed tests extending ClusterManagerLDAPTestBase to use server-auth-provider=NONE
and test that …

[SNAP-2582] allow for NONE as a valid policy for server-auth-provider

---

core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala
core/src/test/scala/org/apache/spark/sql/streaming/SnappyStoreSinkProviderSuite.scala

- Removing multiple records with the same key columns from the incoming batch by grouping record by key columns and picking the last record. This approach may work only when data in the in-coming dataframe batch is partitioned by key columns and the record order is maintained on each partition.
- An optional parameter with key `conflation` is exposed for `snappysink` default callback implementation. This parameter controls the conflation behavior.  The valid values for this parameter is `true` or `false`. By default conflation is enabled, it can be disabled by explicitly setting this parameter to `false`.
- If `HashAggregateSize` property of `SnappySession` is set to default then it is set to `10m` (10 MB) before processing the batch and resetting it back to default `0` after processing …

Removing duplicate key events while processing streaming batch in default sink callback 

---

core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala
core/src/test/scala/org/apache/spark/sql/streaming/SnappyStoreSinkProviderSuite.scala

Disabling conflation by default in default snappy streaming callback
have run following suites: SnappyStoreSinkProviderSuite, SnappyStructuredKafkaSuite, SnappySinkProviderDUnitTest
N/A
N/A

Disabling conflation by default in default snappy streaming callback

---

core/src/main/scala/org/apache/spark/sql/streaming/DirectKafkaStreamSource.scala
core/src/test/scala/org/apache/spark/sql/kafka010/SnappyStreamingKafkaSuite.scala

Making startingOffsets property optional as spark's streaming API takes care of that by using committed offset or kafka param "auto.offset.reset" if no explicit value is set for startingOffsets
Updated SnappyStreamingKafkaSuite test scenario to test streaming without passing "startingOffsets" param

Fix for SNAP-2645:

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/SnappyJoinSuite.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/SnappyJoinLike.scala
core/src/main/scala/org/apache/spark/sql/execution/joins/SnappySortMergeJoinExec.scala
core/src/main/scala/org/apache/spark/sql/internal/JoinQueryPlanning.scala
core/src/test/scala/org/apache/spark/sql/store/SnappyJoinSuite.scala
dunit/src/main/java/io/snappydata/test/dunit/standalone/ProcessManager.java

For queries like:
```sql
select * from t1 join t2 on (t1.c1 = t2.c1)
where t1.c2 = (select max(c2) from t2 where t1.c1 = t2.c1)
```
when t1, t2 are partitioned on c1, should not result in a shuffle. This PR adds a change to
determine underlying attributes across aggregate projection alias columns.
- drill down into the underlying attribute beyond aggregate plans when checking for
partitioning columns matching with join keys
- skip join hint for hash/broadcast in case estimated size is too large because
it can result in OOME with warning that session properties need to be set explicitly
precheckin
NA
NA

[SNAP-2656] check for underlying Attribute with joins on aggregate columns

---

core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala

Reset the pool at the end of collect to avoid spillover of lowlatency pool setting to later operations that
may not use the CachedDataFrame execution paths.
precheckin
NA
NA

[SNAP-2659] reset pool at the end of execution

---

core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

Plan caching for LocalRelations is being disabled as they were giving wrong results.
Added a unit test.
None
No

Disabled plan caching for LocalTableScanExec as well.

---

compatibilityTests/build.gradle
compatibilityTests/src/test/scala/org/apache/spark/sql/SnappyFileStreamSinkSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/SnappyFileStreamSourceSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/execution/streaming/SnappyForeachSinkSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/execution/streaming/SnappyStreamMetadataSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/execution/streaming/SnappyTextSocketStreamSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/kafka010/SnappyKafkaSinkSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/kafka010/SnappyKafkaSourceSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/streaming/SnappyMemorySinkSuite.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/streaming/test/SnappyDataStreamReaderWriterSuite.scala

- Adding some more compatibility tests for structured streaming
- Enabling few passing tests which were ignored earlier
have run the `:snappy-compatibility-tests_2.11:scalaTest` task. there are no code changes involved in this changes.

SNAP-2723 : streaming compatibility tests

---

dtests/src/test/java/io/snappydata/hydra/ao/loadDataPerformance.bt
dtests/src/test/java/io/snappydata/hydra/ao/loadDataUsingDataFrameFromCSV.conf
dtests/src/test/java/io/snappydata/hydra/ao/loadDataUsingDataFrameFromParquet.conf
dtests/src/test/java/io/snappydata/hydra/ao/loadDataUsingExternalTableFromCSV.conf
dtests/src/test/java/io/snappydata/hydra/ao/loadDataUsingExternalTableFromParquet.conf
dtests/src/test/scala/io/snappydata/hydra/ao/LoadData.scala

1. Using DataFrame from csv
2. Using DataFrame from parquet
3. Using externalTable from csv.
4. Using externalTable from parquet.
Ran the new created tests.
N/A
N/A

Automated hydra test to calculate load time for tables in different ways

---

core/src/main/scala/org/apache/spark/sql/execution/ddl.scala

Check if there are servers with offheap setting and if so store them in offheap.

Store the temporary join result in offheap

---

cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/TAQTest.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala

- pass the query string along to SnappyCacheTableCommand to display in GUI
- removed the extra DS.count() and instead pass back the count of cached batches from cache query
- put into will pass "CACHE FOR (sql)" string if SQL is available else use "PUT INTO <plan>"
when using putInto API
- also changed CACHE TABLE <table> without query to use off-heap route if enabled,
and display the full plan in GUI as done for the query case
- set SQL text as Spark job description to show in the jobs/stages tabs in the UI
precheckin
NA
NA

[SNAP-2773] improve GUI display of put into

---

cluster/src/test/scala/io/snappydata/QueryTest.scala
core/src/main/java/org/apache/spark/sql/internal/SnappySharedState.java
core/src/main/scala/io/snappydata/impl/SmartConnectorRDDHelper.scala
core/src/main/scala/io/snappydata/sql/catalog/ConnectorExternalCatalog.scala
core/src/main/scala/io/snappydata/sql/catalog/SmartConnectorHelper.scala
core/src/main/scala/io/snappydata/sql/catalog/SnappyExternalCatalog.scala
core/src/main/scala/io/snappydata/sql/catalog/StoreHiveCatalog.scala
core/src/main/scala/io/snappydata/sql/catalog/impl/SmartConnectorExternalCatalog.scala
core/src/main/scala/io/snappydata/sql/catalog/impl/StoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatchCreator.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/sources/StoreDataSourceStrategy.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyHiveExternalCatalog.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala

Broadcast/exchange reuse was not happening for column/row tables because the scans
had RDD and BaseRelation objects in their case classes so the equality match against
similar scan but having different objects for those two failed.
- added overrides for sameResult to both column and table scans that depends only on the table name
and schema of the output projection
- added a unit test for checking reuse of exchange/broadcast in QueryTest
- corrected the code to avoid two execution display in SQL tab for CTAS (was missing
the check against CreateTableUsingCommand)
- enhanced the data path in ExternalTableMetadata to include locationUri's for file based stores,
URL for JDBC sources masking the password portion
precheckin; TPC-DS run will be manually confirmed
Add a note that dashboard …

[SNAP-2789] implement sameResult for table scans

---

cluster/src/dunit/scala/io/snappydata/cluster/DDLRoutingDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
cluster/src/test/scala/io/snappydata/cluster/QueryRoutingSingleNodeSuite.scala
cluster/src/test/scala/org/apache/spark/sql/store/SQLMetadataTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyHiveExternalCatalog.scala
core/src/test/java/io/snappydata/api/JavaCreateIndexTestSuite.java
core/src/test/scala/io/snappydata/SnappyFunSuite.scala
core/src/test/scala/org/apache/spark/sql/store/MetadataTest.scala
core/src/test/scala/org/apache/spark/sql/store/ViewTest.scala
dtests/src/test/java/io/snappydata/hydra/smoke.sh
gradle.properties

- previous changes set SparkContext.SPARK_JOB_DESCRIPTION property to the query string
for SnappySession.sql executions but this can exceed 32K and property will fail in
serialization, so trim it to 100 size with "..." continuation like done in SQL tab display
- added large view test to ViewTest and enhanced it to accept a generic "String => DataFrame"
closure so that the same can be used for scala tests for SnappySession as well as dunits
for JDBC Statement.execute; added the same tests to DDLRoutingDUnitTest using this
Note: the above test is unable the reproduce the original issue with CREATE VIEW but it does
reproduce for a large query string
- disallow CREATE INDEX creation on column tables without experimental-features property
- clear catalog cache in shutdown to avoid its …

[SNAP-2818] trim the JOB_DESCRIPTION property in Spark jobs

---

core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala
core/src/test/scala/org/apache/spark/sql/streaming/SnappyStoreSinkProviderSuite.scala

skipping putinto and deletefrom operation in the sink if incoming batch doesn't contain any update or delete events
- SnappyStoreSinkProviderSuite is passing
- manual testing

SNAP-2807 - skipping putinto and deletefrom operations in the sink if not required

---

core/src/main/scala/io/snappydata/util/ServiceUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala

using off-heap storage for caching data inside snappy sink
Changes for limiting cache size (by some configurable property) is tracked separately by https://jira.snappydata.io/browse/SNAP-2829
- precheckin 
- manual testing

Snap 2761- using off-heap storage for caching data inside snappy sink

---

cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala

Using "create" , which does not allow duplicates - solves unique alias name issue.
* Use "create" instead of "put" 
* Catching EntryExistsException explicitly; otherwise it categorises it as severity 0 and closes the connection
Ran precheckin

Fix to enforce unique alias names to packages - deploy package command

---

core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala
core/src/test/scala/org/apache/spark/sql/streaming/SnappyStoreSinkProviderSuite.scala

- skipping _eventType column handling from conflation logic when input dataframe doesn't contain _eventType column
- throwing AnalysisException when target table doesn't contain
key columns or primay key
added tests in SnappyStoreSinkProviderSuite

[SNAP-2869] handling conflation when _eventType column is not available in input

---

cluster/sbin/snappy-leads.sh
cluster/sbin/snappy-locators.sh
cluster/sbin/snappy-nodes.sh
cluster/sbin/snappy-servers.sh
cluster/sbin/snappy-start-all.sh
cluster/sbin/snappy-stop-all.sh

To take config files from that folder instead of default conf folder.
Please note log4j.properties file is still taken from the default conf folder.
Will fix this anomaly later.
Manual. QA is also verifying as it has been done mainly for them.

A --config directory can be passed to the snappy-start-all script

---

build.gradle
jdbc/build.gradle

Removed the spark classes from the snappy-jdbc.jar It was containing the spark classes of the org.apache.spark.unsafe package, snappy-jdbc.jar was causing an issue while using it in the spark 2.3.1 version.
Yes
No
No

Branch 1.0.2.2

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
core/src/main/scala/io/snappydata/util/ServiceUtils.scala

Set default value for spark.sql.files.maxPartitionBytes in snappy to 32mb. User can change the value if required. 
Verified the patch manually
The setting of 32mb has been verfied by Swati/Sonal using parquet, csv and ORC formats

Set default value for spark.sql.files.maxPartitionBytes to 32mb

---

build.gradle

Generating SparkR library along with snappy product.
Note that building SparkR library required R installed on the build machine.
Hence by default `./gradlew product` will not build SparkR library and it will not be included as part of
snappy's distribution.
sparkR library can be included as part of product distribution by passing `R.enable` build property.
Using R version `3.5.3`
manually launched `bin/sparkR` shell and tried some CRUD SQL queries using `sql()` function of sparkR
https://github.com/SnappyDataInc/spark/pull/141

generating SparkR library along with snappy product

---

cluster/src/main/scala/io/snappydata/gemxd/SnappyDataVersion.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyMemberDetailsPage.scala

1. Adding product Edition type in version information
2. Changing App Name from SnappyData to TIBCO ComputeDB
3. Renaming pages to just Dashboard, Member Details and Jobs
4. Removing or Changing user visible SnappyData references on UI to TIBCO ComputeDB.
- Yes
Spark: https://github.com/SnappyDataInc/spark/pull/150

Changes for SNAP-2974: Snappy UI re-branding to TIBCO ComputeDB

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/RemoteEntriesIterator.scala
core/src/main/scala/org/apache/spark/sql/store/StoreUtils.scala
encoders/src/main/scala/org/apache/spark/sql/collection/SharedUtils.scala

- Issue is not insert specific rather is in RemoteEntriesIterator where
statsRows iterator does a fetchNextBatch in its next method (around line
130). 
- In addition to fetching the next batch this causes the current batch values to be freed. So the higher level iterator ColumnBatchIterator looks at the last value but finds it to be empty
buffer so skips it. As a result iteration over remote entries
consistently misses one ColumnBatch per 1000 (which is the size of a
batch of keys fetched in RemoteEntriesIterator).
Yes. 
As discussed in the meeting patch is verified and tested manually also.
No
No

SNAP-2902 Mismatch in the expected and actual inserted rows

---

core/src/main/java/org/apache/spark/sql/internal/SnappySharedState.java

Fix for SNAP-2982 from Sumedh
Lead node and server both made a version entry in the metastore to initialise the HiveClient. However only one version entry is expected in the
metastore. It breaks while instantiating SessionHiveMetaStoreClient and hence leader does not come up.
The Hive client initialization in StoreHiveCatalog.CatalogQuery#call takes a distributed lock to prevent concurrent initialization of Hive client
by different servers and prevents such scenarios. However on lead node, SnappySharedState constructor also initializes a Hive client which is not
guarded by this lock. The fix just ensures that StoreHiveCatalog is initialized before trying to get Hive client in SnappySharedState.
Will be merging the fix as discussed in team meetings
The fix has been manually verified by …

Fix for SNAP-2982

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
compatibilityTests/build.gradle
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/main/scala/io/snappydata/Literals.scala
docs/howto/concurrent_apache_zeppelin_access_to_secure_snappydata.md
docs/howto/connect_jdbc_client_pool_driver.md
docs/howto/connect_using_jdbc_driver.md
docs/howto/using_snappydata_for_any_spark_dist.md
docs/programming_guide/spark_jdbc_connector.md
encoders/build.gradle
jdbc/build.gradle
launcher/src/main/java/io/snappydata/tools/QuickLauncher.java

- changed default of hive-thriftserver to true
- to reduce startup time, the default behaviour is to launch the thrift server
in background with startup message stating: Starting ... (without host/port information)
- if snappydata.hiveServer.enabled=true is explicitly provided then the hive thriftserver
is launched in foreground with proper host/port information like before
precheckin
docs update to mention that hive-thriftserver is started by default in background
NA

Start hive-thriftserver by default in background

---

cluster/src/test/scala/org/apache/spark/sql/MiscTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionCatalog.scala

For single table this workaround will work. But for tables with same name
but in different schema it will have issues. Will be revisited as part of
SNAP-2442
Catching Analysis exception and checking if it is a resolution issue and if UnresolvedStar or UnresolvedAttribute kind of node is present in the execution plan. If yes then replace them by just star or minimally qualified column name.
Unit test added. Precheckin underway.
None.

Worakaround fix for SNAP-2440.

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatchIterator.scala
encoders/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnDeltaEncoder.scala
encoders/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEntry.scala
encoders/src/main/scala/org/apache/spark/sql/store/CompressionUtils.scala

- release compression buffer if compression has been determined to be ineffective
- release positions array buffer created by ColumnDeltaEncoder
precheckin -Pstore
NA
https://github.com/SnappyDataInc/snappy-store/pull/474

Fix buffer reference count for couple of cases

---

cluster/src/main/scala/io/snappydata/gemxd/SnappyDataVersion.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala

1. Setting product name to SnappyData if it is community edition else TIBCO ComputeDB.
2. Loading GFXD version properties to identify correct product type
- Tested Manually
Yes
**Spark:** https://github.com/SnappyDataInc/spark/pull/151

Code changes for SNAP-2989: Snappy UI rebranding to Tibco ComputeDB iff it's Enterprise Edition 

---

core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala

For OR and AND filter there could be cases where left or right side could be unhandled causing empty parenthesis. This causes syntax error. Now appending 'FALSE' or TRUE in case of OR or AND filter respectively.

Avoid empty parenthesis for unhandled filter

---

core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

- search through all pre-defined key names case-insensitively for set/unset of SQLConf properties
- added check for planCaching property for the same
precheckin
mention that SQLConf property names are case-insensitive
NA

Make SnappyConf key name search case-insensitive

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/execution/CatalogStaleException.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala

Resetting commonStatementAttributes for thrift connection as part of task completion listener making sure it will always reset.
- Manually tested using `JavaCdcStreamingTestSuite`
- Added a SplitCluster dunit test to verify that CatalogStaleException is resolved on retry
- precheckin

[SNAP-3022] - Resetting commonStatementAttributes for thrift connection

---

cluster/src/dunit/scala/io/snappydata/cluster/PreparedQueryRoutingDUnitTest.scala
cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionCatalog.scala

In case of views, to return LogicalPlan, SnappySessionCatalog#lookupRelation() parses the SQL text for view using sessionState.sqlParser.  For PreparedStatements this resets SnappyParser#_questionMarkCounter thereby causing the inconsistency. Now using a new instance SnappySqlParser to parse the view text.
Added unit tests for prepared statements on views
Also added a test for SNAP-3007
precheckin
NA

Prepared stmt on views gives error [SNAP-2254]

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/execution/CodegenSparkFallback.scala

- In CachedDataFrame#collectWithHandler, for one case, query/job is run using sc.runJob(). Here if sc.runJob fails due to stale catalog, there was no code invalidate the cached metadata and retry the query. Added this code.
- Added a dunit test
New dunit test
precheckin
NA
NA

Added a fix and test for SNAP-3024

---

core/src/main/scala/org/apache/spark/sql/internal/SnappySessionCatalog.scala

This avoids the exception thrown when setting 'sys' as current schema via beeline.[SNAP-2972]
* Skip setting current database in case of 'sys' schema.
Tested manually; precheckin running.

Avoids setting currentDatabase as 'sys' in hive's SessionState.

---

cluster/sbin/snappy-nodes.sh
cluster/sbin/snappy-start-all.sh

As per requirement, added code in snappy-nodes.sh to copy the configuration files present in "conf" directory into other members of the cluster. Files present in "conf" are log4j.properties, spark-env.sh, spark-defaults.conf,snappy-env.sh, slaves, servers, leads, locators, metrics.properties,fairscheduler.xml, debug.conf.template,docker.properties. Along with these files if the user has its own configuration files, copy those files as well.
Following use case has been taken care:
1- If cluster running in localhost then do not copy, even though the configuration file configured with IP address and host-name.
2- Do not copy files with ".template" extension
3- Replace the leads, locators, servers files, with existing one other member of the cluster but inform the user about it and keep the …

Added code to copy the configuration files into other member of cluster

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala
core/src/test/scala/org/apache/spark/sql/streaming/SnappyStoreSinkProviderSuite.scala

Retrying streaming batch processing for the snappy sink when `CatalogStaleException` is encountered.  
Currently, number of attempts are set to 10 wtih backoff interval of `100 * attempt_number` millis.   
Also exposed an internal property (`internal___attempts`) to overwrite this for tests.
Added a Dunit test, added scala tests

[SNAP-3023] Handle CatalogStaleException with retries in snappy sink

---

cluster/src/main/scala/io/snappydata/gemxd/SparkSQLPrepareImpl.scala
cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala

Fix for SNAP-3082
Avoid error being thrown when PreparedStatement.setDouble is used for comparison with decimal column.
The issue is seen when for a comparison with decimal column a double parameter is set (using PreparedStatement#setDouble).  The double value 0.9 set in this test actually gets set as 0.90000000000000002220446049250313080847263336181640625  (with precision of 53) and the error is seen as Decimal can not support precision more than 38.
We do allow insert of such a value by normalizing it to target column's precision/scale also for unprepared statements.  Using similar approach in this case as well.
Added a unit test for the scenario. Comparing results of prepared and unprepared statements to make sure that results are correct.
precheckin
NA
NA

Avoid error being thrown when PreparedStatement.setDouble is used for comparison with decimal column

---

core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala
core/src/test/scala/org/apache/spark/sql/store/RowTableTest.scala

* Add support for these(cascade/restrict) keywords in the parser code of alter table
* Add new parameter to alterTable method(s).
* Append the keyword(cascade/restrict) to the sql string that is fired on Gemfire layer.
Ran Precheckin
An optional parameter, named referentialAction, has been added.

Add support for RESTRICT and CASCADE - Alter table drop column

---

core/src/main/scala/io/snappydata/TableStatsProviderService.scala

- Hiding internal sink state table "SNAPPYSYS_INTERNAL____SINK_STATE_TABLE" from UI.
- NA
- None

SNAP-2947 : Hide internal sink state table from UI

---

core/src/dunit/scala/io/snappydata/cluster/CassandraSnappyDUnitTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala

- Adding dunit test for SNAP-3010
- updating the cassandra dunit test to download Cassandra distribution in
`$GRADLE_USER_HOME/cassandraDist` or `$HOME/.gradle/cassandraDist`
directory instead of downloading in distributions directory. The
distribution directory gets cleaned up every time precheckin or
clean build is run causing the download of complete Cassandra distribution
every time.
This PR contains changes in tests itself. Affected tests are passing.
https://github.com/SnappyDataInc/spark/pull/158

Adding dunit test for SNAP-3010

---

core/src/main/scala/org/apache/spark/sql/catalyst/expressions/ParamLiteral.scala

Use synchronizedMap for DynamicReplacableConstant#termMap to avoid it getting corrupted when same ParamLiteral is used concurrently in multiple threads. 
This fixes SNAP-2764 (seen in case of subqueries). 
precheckin
NA
NA

Use synchronizedMap for DynamicReplacableConstant#termMap

---

cluster/src/main/scala/org/apache/spark/status/api/v1/TableDetails.scala
cluster/src/main/scala/org/apache/spark/status/api/v1/snappyapi.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala
core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

- Adding Redundancy column in Tables List to view count of redundant copies.
- Adding Redundancy Status column in Tables List to monitor redundancy has been satisfied or broken.
- Changes for maintaining Redundancy and isRedundancyImpaired details for count of redundant
copies and redundancy satisfaction/broken status.
- Yes, to be updated.
**Spark:** https://github.com/SnappyDataInc/spark/pull/160
**Store:** https://github.com/SnappyDataInc/snappy-store/pull/495

Code changes for SNAP-2779 and SNAP-1338:

---

core/src/test/scala/io/snappydata/util/ODBCDriverTestSuite.scala
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/rowTableCPP/local.rowTableCPPTest.conf
dtests/src/test/java/io/snappydata/hydra/rowTableCPP/rowTableCPPTest.bt
dtests/src/test/java/io/snappydata/hydra/rowTableCPP/rowTableCPPTest.conf
dtests/src/test/java/io/snappydata/hydra/rowTableCPP/serverHA.inc

[##](url) Changes proposed in this pull request
Added automated test for ODBC Failover functionality
NA
NA
This PR linked to generated PR in snappy-store [https://github.com/SnappyDataInc/snappy-store/pull/480](url)

Added automated test for ODBC FailOver functionality

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerLDAPTestBase.scala
cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitSecurityTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala
core/src/main/scala/io/snappydata/sql/catalog/SnappyExternalCatalog.scala
core/src/main/scala/io/snappydata/sql/catalog/impl/StoreHiveCatalog.scala

* Mask credentials (in case of s3 URI) in Describe extended/formatted output.
* Mask credentials in case of s3 on UI for external tables.
* Disallow access non-admin user to the tables in SNAPPY_HIVE_METASTORE.
* Added tests for the fixes.
Precheckin is in progress

Fixing [SNAP-2653]

---

cluster/src/main/java/org/apache/spark/streaming/JavaSnappyStreamingJob.java
cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
cluster/src/main/scala/org/apache/spark/executor/SnappyExecutor.scala
cluster/src/main/scala/org/apache/spark/util/SnappyUtils.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/dunit/scala/org/apache/spark/SparkUtilsAccess.scala
core/src/main/scala/io/snappydata/ToolsCallback.scala
core/src/main/scala/org/apache/spark/sql/internal/JarUtils.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionCatalog.scala

- Including all the jar urls at the time of sending the list to executors.
precheckin is clean,
Basic unit test is added,
Manually tested.
Will add more testcases but the source changes are ready to be reviewed.
NA

Fix for SNAP-3069: Executing two UDFs one-after another throws ClassNotFoundException

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
core/src/main/scala/io/snappydata/util/ServiceUtils.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyHiveExternalCatalog.scala

Five hive properties set the "scratch" and other directories to be inside working directory instead of
/tmp directory so that there is no trouble if multiple instances try to use it (else directory
created by some instance may be unwritable by another)
- set SCRATCHDIR, LOCALSCRATCHDIR, DOWNLOADED_RESOURCES_DIR,
HIVEHISTORYFILELOC and HIVE_SERVER2_LOGGING_OPERATION_LOG_LOCATION
as subdirectories inside working directory + "/hive"
- set as system properties so that will be used by default by all sessions by default and still can be
overridden by hive-site.xml; additionally builtin catalog always overrides to the defaults
- use putIfAbsent/setIfMissing methods to overwrite if not present instead of check+set
precheckin
NA
NA

SNAP-3094: change default hive tmp file locations to working directory

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala

if schema name of individual attributes within analyzed plan is not present, instead of assigning currentschema we are assigning blank
ran precheckin
no
none

SNAP-1327: making schemaname empty if it isn't present in plan

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitSecurityTest.scala
core/src/main/scala/io/snappydata/sql/catalog/impl/StoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyHiveExternalCatalog.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionCatalog.scala

- older releases have schema with upper-case column names so always
"normalize" schema to lower-case names when reading from SnappyHiveExternalCatalog
- also change targetTable property in policy to lower-case
precheckin and manual upgrade testing
NA
NA

SNAP-3090: normalize schema when reading from catalog

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerTestBase.scala
dunit/src/main/java/io/snappydata/test/dunit/DistributedTestBase.java

By default it is ON but tests have an option to ignore it. Similarly users
can ignore it too.
Running precheckin
https://github.com/SnappyDataInc/snappy-store/pull/502

Adding a system property flag to make reserve configurable.

---

core/src/main/scala/io/snappydata/sql/catalog/impl/StoreHiveCatalog.scala
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala

- In StoreHiveCatalog.CatalogQuery#initCatalog, instead of creating a new SparkConf, use existing SparkConf if available in SparkEnv. This avoids properties getting loaded from system properties as in case of new SparkConf object.
- Remove username/password from cloned spark conf as Spark conf does not contain the password. Username/password is later filled in by getOrCreateExternalCatalog() from bootProperties
- In HiveClientUtil added a NULL check for property values
Above changes are done with @sumwale by code inspection as a possible fix for SNAP-3013 (NPE in org.apache.spark.SparkConf.set for maxPartitionBytes) which is not readily reproducible. 
precheckin 
30 runs of hydra tests mentioned in SNAP-3013
NA

Instead of creating a new SparkConf, use existing SparkConf in StoreHiveCatalog.CatalogQuery#initCatalog

---

core/src/main/scala/io/snappydata/functions.scala
core/src/main/scala/org/apache/spark/sql/SnappyContextFunctions.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/policy/policyFunctions.scala

- added proper ExpressionDescription tags for the extra builtin functions
for doc generation
- created static list of functions in SnappyDataFunctions filling information
using the above tags instead of hard-coding in registration code
- centralized function registration to be via SnappyContextFunctions.registerSnappyFunctions
precheckin buildSqlFuncDocs
NA
https://github.com/SnappyDataInc/spark/pull/169
https://github.com/SnappyDataInc/snappy-aqp/pull/192

Cleanup function registration using ExpressionDescription tags

---

cluster/sbin/snappy-nodes.sh
cluster/sbin/snappy-start-all.sh
launcher/src/main/java/io/snappydata/tools/QuickLauncher.java

and if already running is in "running" state. This differentiation is required in start all script for starting lead members.
The start up script carefully decides based on the exit status of the servers
where at least one server is in "running" state and then only starts lead members.
Manuall testing
https://github.com/SnappyDataInc/snappy-store/pull/511

Change in the exit status if already running is in "waiting"

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala

`REPAIR_CATALOG` store procedure was failing internally while fixing inconsistent catalog
entry for sample tables. Hence inconsistency related to sample table were not getting fixed
by `REPAIR_CATALOG`.  
This is because sample table can not be dropped without destroying the corresponding
reservoir region.  
To fix this we are destroying reservoir region of a sample table before attempting to
drop the table as part of `REPAIR_CATALOG` stored procedure. Along with the reservoir
region, we are also clearing cached sampler entry for the sample table. For this one new
boolean parameter (namely `removeSampler`) is introduced in
`CREATE_OR_DROP_RESERVOIR_REGION` stored procedure.
- added dunit tests
- `precheckin -Pstore`
https://github.com/SnappyDataInc/snappy-store/pull/513 …

[SNAP-3110]  Fixing catalog inconsistency for sample tables 

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala

Re-merging changes for SNAP-3110 with the fix for backward compatibility.
Earlier we introduced a new parameter for the procedure
`CREATE_OR_DROP_RESERVOIR_REGION`. This can break the upgrade from older
versions while DDL replay. Instead of exposing extra parameter for removal of sampler,
we are not removing it always along with the reservoir region.
Fixing failing test `AQPCatalogConsistencyDUnitTest`
- `AQPCatalogConsistencyDUnitTest` passing
- will trigger `precheckin -Pstore`
https://github.com/SnappyDataInc/snappy-aqp/pull/194
https://github.com/SnappyDataInc/snappy-store/pull/514

[SNAP-3110] Changes for SNAP-3110 with fix for backward compatibility 

---

core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala
core/src/main/scala/org/apache/spark/sql/internal/session.scala

- change nodeName to "SampleTableScan" instead of ColumnTableScan for sample table scans
- also fixed CTAS for sample table to show up in GUI by posting separate GUI
plan for the same
precheckin
NA
NA

[SNAP-3137] use "SampleTableScan" in GUI for sample table scan

---

cluster/src/dunit/scala/io/snappydata/externalstore/JDBCPreparedStatementDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLPrepareImpl.scala
cluster/src/test/scala/io/snappydata/cluster/PreparedQueryRoutingSingleNodeSuite.scala
cluster/src/test/scala/io/snappydata/cluster/QueryRoutingSingleNodeSuite.scala
cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/aggregate/CollectAggregateExec.scala
core/src/main/scala/org/apache/spark/sql/execution/ui/SnappySQLListener.scala

- moved executionId clear after RDD evaluation
- use common method to create SQLExecutionUIData for SparkListenerSQLPlanExecutionStart
and SparkListenerSQLExecutionStart
- add to activeExecutions in SparkListenerSQLPlanExecutionStart too so that it shows up in GUI
in case RDD evaluation takes long (e.g. for ORDER BY or subqueries)
- handle case of Union(commands) and treat like other ExecuteCommandExec/ExecutePlans are
- handle exception cases in CollectAggregateExec to clear any blocks in BlockManager
- clear plan cache for session when connection is closed; updated tests to expect the same
precheckin
NA
NA

[SNAP-3123] encapsulate any jobs in RDD evaluation under same executionId

---

cluster/src/test/scala/org/apache/spark/sql/SchedularPoolTest.scala
core/src/dunit/scala/org/apache/spark/sql/streaming/SnappySinkProviderDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappySessionState.scala
core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala
core/src/main/scala/org/apache/spark/sql/streaming/SnappyStreamingQueryManager.scala
core/src/test/scala/org/apache/spark/sql/streaming/SnappyStoreSinkProviderSuite.scala

SnappySessionState maintained as part of SnappySession is not thread-safe. Hence running multiple streaming queries (which run in separate threads) may lead to issues related to thread safety.
With this change, we are checking whether another streaming query with Snappysink is already running in the SnappySession before starting a streaming query with SnappySink.
Added scalatest, precheckin

[SNAP-3033] Validating whether at max one streaming query with snappysink is active in a SnappySession

---

core/src/main/scala/org/apache/spark/sql/execution/oplog/impl/OpLogRdd.scala

maintaining a reference to direct bytebuffers till compute of OpLogRdd is complete so as to prevent buffer getting released thereby avoiding hs error
ran individual module tests and recovery tests
no
none

hs error fixes in dataextractor

---

core/src/main/scala/org/apache/spark/sql/SnappySession.scala

**Problem:** [SNAP-3253] Few Cluster and AQP tests are failing with InvocationTargetException after introducing structured streaming ui feature
**Cause:** 
Structured streaming UI tab is created when SparkSession instance is created. But while creating SnappySession (which extends SparkSession class) instance, it requires gemfire cache be created before its instance is created. But SparkSession makes calls to add structured streaming tab before instance is initialised and which becomes bottle neck here.  
**Changes:**
- Adding method updateStructuredStreamingUITab which calls parent classes method
updateUIWithStructuredStreamingTab using reflection.
This method creates or updates Structured Streaming UI Tab.
- Adding call to updateStructuredStreamingUITab for each SnappySession object …

Fixes for SNAP-3253:

---

cluster/bin/snappy
cluster/sbin/snappy-nodes.sh

* [SNAP-3229] Fix an issue with earlier commit where even non-local members were treated as localhost and launch-commands were fired locally instead of via ssh. This was caused by a faulty `if` check in `snappy-nodes.sh` script.
Manually tested:
1. Single/Multi instance cluster on AWS. Single-instance with/without passwordless ssh setup.
2. Single/Multi node cluster on laptop
3. Multi-node cluster on two physical hosts
NA
NA

* [SNAP-3229] Fix an issue with earlier commit where even non-local members were treated as localhost.

---

cluster/sbin/snappy-nodes.sh

* Skip the "hostname -I" check in snappy-nodes.sh for Mac OS.
Manual testing:
1. Single node cluster with/without passwordless ssh on Mac OS
2. Single/Multi node cluster on laptop/different physical hosts for sanity
NA
NA

* Skip the "hostname -I" check in snappy-nodes.sh for Mac OS.

---

python/pyspark/sql/snappy/snappysession.py

`createTable` API was failing when used without passing explicit values for
provider and schema.
By default API defaults provider parameter to `parquet` and the schema can
also be retrieved from parquet file.
Usage example: snappy.createTable("table1",path ="/path/to/file.parquet")
Manually tested using `pyspark` shell. Have written unit test but somehow 
`checkPython` target is not picking up the test. Will analyze further and add it
later.

[SNAP-3262] Fixing createTable API for python

---

core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/execution/ExistingPlans.scala

Default retry of spark tasks on failure can cause duplicate in case of insert operations.
Provided a user property snappydata..maxRetryAttemptsForWrite, which user can set to 0 to avoid this scenario.
Other, operations as usual will retry without causing any consistency issue.

Provide option to not retry Insert operation

---

core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappySessionState.scala
core/src/main/scala/org/apache/spark/sql/streaming/SnappyStreamingQueryManager.scala

- call HashAggregateSize.set(conf, "-1") has been shifted from
SnappySessionState.streamingQueryManager to SnappyStreamingQueryManager.
- Ran failing tests again and verified that those are not failing again.
- None
- None

Fixes for SNAP-3264:

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
core/src/main/scala/io/snappydata/recovery/RecoveryService.scala
core/src/main/scala/org/apache/spark/sql/execution/oplog/impl/OpLogRdd.scala

* Add property to enable table count on UI in recovery mode
* Show count as -1, when error while in table scan
Ui will appear as is Recovery Mode, expect the table counts.To see table counts user need to set the property snappydata.recovery.enableTableCountInUI to true. By default the property is set to false and the table count will be shown as -1.
When the table counts is enabled, if there is an error while reading a particular table, it's count will be -1.
Manual testing

SNAP-3247; Disable/skip table count on UI in recovery mode.

---

compatibilityTests/src/test/scala/org/apache/spark/sql/SnappyJDBCSuite.scala
core/src/main/scala/io/snappydata/util/ServiceUtils.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala

we are capturing exact ddl string provided and adding it to corresponding catalog table. This is needed so that EXPORT_DDLS procedure can return original ddls.
This PR masks passwords if any provided in ddls
Precheckin looks fine
no
no

masking creds before capturing into catalog

---

cluster/src/dunit/scala/io/snappydata/externalstore/JDBCPreparedStatementDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala

Index variable tracking reference type fields was not getting incremented
when a reference type column is set to null. Fixing this behavior by
incrementing the index variable at the correct place.
Note that this issue was affecting JDBC connection mode only. Queries run
using `SnappySession#sql` were not affected.
- added dunit test

Snap 3275 - incrementing the index variable for null values for reference type

---

cluster/src/main/scala/io/snappydata/remote/interpreter/SnappyInterpreterExecute.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala

An extra colon (:) was getting inserted between keyword `LDAPGROUP` and actual group name, causing the failure. Removed that.
Added a testcase which is passing.
NA
NA

Fix for SNAP-3281

---

build.gradle
cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
cluster/src/main/scala/io/snappydata/remote/interpreter/SnappyInterpreterExecute.scala
core/build.gradle
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
jdbc/build.gradle

- Used `catalogTable.database` instead of `catalogTable.owner` to get the table owner (schema).
- Fixed the issue in extracting the schema name from identifier.
- Used capitalized form of LDAP group name in `PermissionChecker.addRemoveUserForKey()` . This fixed an issue where if a user specified non-capitalized LDAP group name in GRANT/REVOKE DDL for external tables, it failed.
- If a username is found to be null during checking authz for external tables, set it to empty string and proceed to authz instead of returning without authz.
- Added several new testcases in the dunit test.
Added new testcases.
Precheckin is clear.
NA
NA

Fixes for SNAP-3280 and SNAP-3284

---

core/src/main/scala/io/snappydata/recovery/RecoveryService.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala

* Remove orgSqlText key from contextObject once done using.
* Release lock on DataDictionary once done using.
precheckin ran and is clean
no
no

SNAP-3288 cleaning contextObject and releasing read lock on data dictionary

---

build.gradle
cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
cluster/src/main/scala/io/snappydata/remote/interpreter/SnappyInterpreterExecute.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitSecurityTest.scala

* [SNAP-3282] Procedure SYS.REFRESH_LDAP_GROUP now updates the entries in metadata region which are used in authorization of external tables.
* Also fixed an issue where system user could not grant permission on external table of another user.
- Tested manually.
- Added a testcase for second issue.
- precheckin is fine.
NA
NA

* [SNAP-3282] SYS.REFRESH_LDAP_GROUP now updates metadata region also.

---

cluster/src/dunit/scala/io/snappydata/cluster/PrimaryDUnitRecoveryTest.scala
core/src/main/scala/org/apache/spark/sql/execution/oplog/impl/OpLogRdd.scala

* Allowing -1 as value for SchemaColumnId, for the case when the column is missing
in the schema-version under consideration.
Manual testing, Relevant test suite. Precheckin underway.

Fixing SNAP-3306

---

cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/execution/sources/StoreDataSourceStrategy.scala

The purpose of the function collectProjectsAndFilters is to flatten the intermediate Project Nodes.
for eg. if the the tree is  project1 -> filter1 -> project2  -> filter2 -> project-3 -> BaseTable
and if the aim is to have a flattened structure like
project1 -> filters -> base table.
and given that final projected columns in project1 ( the output) may be less  than project2 , project3, the filter2,  may be refering to an attribute which is no longer present in project1. This is resoleved in the function by substituting attribute reference in filter with the Expression present in aliases map with the guarantee that expression in aliases map is for sure part of final projection.
The fix is that while identifying substitutable fields, we only use those fields which are deterministic. And if …

suggested fix for SDENT-171

---

cluster/src/main/scala/io/snappydata/gemxd/ClusterCallbacksImpl.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLPrepareImpl.scala
cluster/src/test/scala/io/snappydata/cluster/PreparedQueryRoutingSingleNodeSuite.scala
core/src/main/scala/org/apache/spark/jdbc/ConnectionConf.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala

The prepare phase of PreparedStatement returns the scale/precision of parameters for routed
queries. This should be set back on SnappySession during execution so that the current set
of parameters are used rather than those set by the last prepare (which can be different)
Also made the PVS info array size uniform to be three ints per type removing the unused
(and incorrect) fourth field which is supposed to have nullability information.
Added unit test for the bug (PreparedQueryRoutingSingleNodeSuite.scala#SNAP-3332)
https://github.com/TIBCOSoftware/snappy-store/pull/567

 [SNAP-3332] set scale/precision array on session in each PreparedStatement execution
