TIBCOSoftware/snappydata

snappy-tools/src/main/scala/io/snappydata/ToolsCallbackImpl.scala

Handle all the gemfirexd store boot properties
minor changes for scala code styling

Handle all the store boot properties

---

snappy-tools/sbin/snappy-nodes.sh

Put the hostname in quotes to prevent zsh issues.

---

snappy-core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/DirectKafkaStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/FileStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/KafkaStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/RabbitMQStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/RabbitMQUtils.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/RawSocketStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/SchemaDStream.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/SocketStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/StreamBaseRelation.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/StreamSqlHelper.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/StreamToRowsConverter.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/TextSocketStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/TweetToRowsConverter.scala
snappy-core/src/main/scala/org/apache/spark/sql/streaming/TwitterStreamSource.scala
snappy-core/src/main/scala/org/apache/spark/streaming/SnappyStreamingContext.scala
snappy-dunits/src/test/scala/io/snappydata/dunit/streaming/TweetToRowsConverter.scala
snappy-tools/src/test/scala/io/snappydata/app/streaming/StreamingSuite.scala

Bug fixes in streaming (SNAP-672, SNAP-394, SNAP-475, SNAP-353)
Added a new unit test
modified existing test 
No Other PR's required.

Fix for SNAP-672, SNAP-394, SNAP-475, SNAP-353

---

docs/aqp.md

I suggest a revision for this phrase: "Reservoir sampling is a technique/set of algorithms for randomly choosing a sample of *k* items from a set S containing n items, where k is a small subset of n." 
Suggestion 1: "...where k is smaller than n."
Suggestion 2: "...choosing a sample T of *k* items from a set S containing n items, where T is a small subset of S."

Typos, formatting, punctuation

---

snappy-core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
snappy-core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
snappy-tools/src/main/scala/org/apache/spark/sql/columntable/ColumnFormatRelation.scala
snappy-tools/src/main/scala/org/apache/spark/sql/columntable/StoreCallbacksImpl.scala

(Fill in the details that how was this patch tested)

Improved formula for better error estimation using closed form method

---

tests/dunit/src/test/scala/io/snappydata/dunit/streaming/StreamingDUnitTest.scala

Moving test to AQP
https://github.com/SnappyDataInc/snappy-aqp/pull/41

Moving test to AQP.

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/snappyParsers.scala

SnappyData build gave warnings for these two files. Corrected code to remove the warning.
clean built the product
NA

Corrected code which used to give warnings.

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala

Enabled code generation for column table scan.
As its only scanning running pre checkin is sufficient. 
NA

Enabled code generation in column table scan.

---

build.gradle

Added installPulse target to copy pulse.war to snappy lib folder.
This target assumes the user has a checkout of Pulse repository . We can also automate this if preferable.
Tested Pulse after running the target
NA

Added installPulse target to copy pulse.war to snappy lib folder.

---

docs/jobs.md

* Correcting the example of streaming job submission as pointed out by Sumedh
and making the content a bit more verbose.
NA
#253
https://github.com/SnappyDataInc/snappydata/commit/f506ca6d303277c8b8fa608e3bd5ea73d9d3c9dc#commitcomment-17569456

* Correcting the example of streaming job submission in docs

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerTestBase.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
cluster/src/main/scala/org/apache/spark/sql/SnappyContextFactory.scala
cluster/src/test/scala/io/snappydata/ServerStartSuite.scala
cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala
cluster/src/test/scala/io/snappydata/tools/LeaderLauncherSpec.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/streaming/SnappyStreamingContext.scala
core/src/test/java/io/snappydata/api/JavaCreateIndexTestSuite.java
core/src/test/scala/io/snappydata/SnappyFunSuite.scala
core/src/test/scala/io/snappydata/app/streaming/StreamingSuite.scala
core/src/test/scala/io/snappydata/gemxd/BasicStoreTest.scala
core/src/test/scala/io/snappydata/util/TestUtils.scala
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
examples/src/main/java/io/snappydata/examples/JavaAirlineDataJob.java

Removed SnappyContext.getOrCreate method. Please see PR SNAP-771_1 for detailed explanation.
precheckin
Related PRs SNAP-771_1 which deals with concurrency of catalog.  AQP SNAP-771_2

Removed SnappyContext.getOrCreate method.

---

docs/GettingStarted.md
docs/jobs.md

documentation python streaming api
NA
(Fill in the details that how was this patch tested)
NA

Added python api documentation

---

README.md

added links to snappy-poc

---

docs/GettingStarted.md

add snappy-poc links

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/concStreamingWithAirlineDataQueries.conf
dtests/src/test/java/io/snappydata/hydra/serialStreamingWithAirlineDataQueries.conf

- Added support for starting of jobs by allowing passing of properties using APP_PROPS.
- Added support for passing various parameters(specifically required for bechmarking work) while starting the server and lead members.
verified the changes by running sample.bt.
No.

Added support for starting of jobs by allowing passing of properties using APP_PROPS

---

core/src/main/scala/org/apache/spark/sql/aqp/SnappyContextDefaultFunctions.scala
core/src/main/scala/org/apache/spark/sql/aqp/SnappyContextFunctions.scala
core/src/main/scala/org/apache/spark/sql/dataFrames.scala

Support for behavior clause in DataFrame API
NA
NA
NA

Added support for behavior clause in DataFrame API

---

core/src/main/scala/org/apache/spark/sql/snappyParsers.scala
core/src/test/scala/org/apache/spark/sql/store/RowTableTest.scala

This PR resolves issue with Create table as Select when Using..Options is not provided
Written a Unit test for this fix in RowTest.scala
N/A

[SNAP-416] Fix for SNAP-416 Support for create table as Select

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/cluster/local.startSnappyCluster.conf
dtests/src/test/java/io/snappydata/hydra/cluster/longRunningTest.bt
dtests/src/test/java/io/snappydata/hydra/cluster/longRunningTest.sh
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataJobs.conf
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataQueries.conf
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataQueriesAndJobs.conf

- Added a fix for issue with running queries in multi host environment.
- Verfiied the changes by running longRunningTest.sh in multi host environment.
NA
No

Added a fix for issue with running queries in multi host environment.

---

dtests/build.gradle
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataJobs.conf
dtests/src/test/java/io/snappydata/hydra/cluster/runAirlineDataQueriesAndJobs.conf
dtests/src/test/java/io/snappydata/hydra/cluster/sample.conf
dtests/src/test/java/io/snappydata/hydra/cluster/sample.inc
dtests/src/test/java/io/snappydata/hydra/cluster/sampleLeadHA.conf
dtests/src/test/java/io/snappydata/hydra/cluster/sampleSnappyStoreHA.conf
dtests/src/test/java/io/snappydata/hydra/cluster/sampleSplitMode.conf
dtests/src/test/java/io/snappydata/hydra/concStreamingWithAirlineDataQueries.conf
dtests/src/test/java/io/snappydata/hydra/serialStreamingWithAirlineDataQueries.conf

- Added support in framework for resubmitting job if failed in case of lead node failover
- Added support for resubmitting the failed job for number of times specified by user
Verified the changes by running sampleLeadHA.conf file
NA
No

Added support in framework for resubmitting job if failed in case of lead node failover

---

core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/test/scala/org/apache/spark/sql/store/SnappyJoinSuite.scala

The result of join of replicated tables should have a local join with any other table.
Added a unit test that analyzes the plan to ensure that no sortMergeJoin is involved with multiple replicated tables and one partitioned table.

The result of join of replicated tables should have a local join with any other table

---

cluster/src/test/scala/io/snappydata/benchmark/snappy/TPCH_Snappy_Query.scala
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyPrms.java
dtests/src/test/java/io/snappydata/hydra/cluster/sampleLeadHA.conf
dtests/src/test/java/io/snappydata/hydra/distJoin/distJoin.bt
dtests/src/test/java/io/snappydata/hydra/distJoin/distJoinWithLeadHA.conf
dtests/src/test/java/io/snappydata/hydra/distJoin/distJoinWithServerHA.conf
dtests/src/test/java/io/snappydata/hydra/distJoin/local.distJoin.conf

- Added test for distributed join with lead and server HA
Verified the changes by running distJoinWithLeadHA.conf and distJoinWithServerHA.conf tests.
NA
No

Added tests for Distributed Join with lead and server HA scenarios

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerTestBase.scala
cluster/src/dunit/scala/io/snappydata/externalstore/ColumnTableDUnitTest.scala

Added dunit for column table persistence with HA.
some code formatting as per snappy stds.
precheckin

added dunit for column table persistence with HA

---

cluster/src/dunit/scala/io/snappydata/cluster/ExecutionEngineArbiterDUnitTest.scala

Added a Dunit for SNAP-936
test execution and store and snappy precheckin
None
https://github.com/SnappyDataInc/snappy-store/pull/101
Execution engine to improve query performance

added test for intelligent determination of

---

cluster/build.gradle

Excluded stock spark binaries while building cluster project

Excluded stock spark binaries while building cluster project.

---

dtests/build.gradle

Excluded stock spark binaries while building dtest

Excluded stock spark binaries while building dtest

---

cluster/conf/fairscheduler.xml

Made the scheduling mode of the default pool as FAIR after a discussion with the team
Did some manual testing. Ran the quick start successfully.

Scheduling mode as fair 

---

docs/aqp_aws.md

* Changed the URL in the documentation
NA
(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?) No
NA

Changed URL in document

---

cluster/src/test/scala/org/apache/spark/sql/NWQueries.scala
dtests/build.gradle

* Removed unwanted dependency and modified few test to use csv function
Modified some existing test and all test passed
(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?) No
https://github.com/SnappyDataInc/snappy-aqp/pull/118

Removed unwanted dependency and modified few test to use csv function

---

cluster/src/dunit/scala/org/apache/spark/sql/NorthWindDUnitTest.scala
cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala
cluster/src/test/scala/io/snappydata/benchmark/TPCHReplicatedTable.scala
cluster/src/test/scala/io/snappydata/benchmark/TPCHTableSchema.scala
cluster/src/test/scala/org/apache/spark/sql/NWQueries.scala
cluster/src/test/scala/org/apache/spark/sql/NorthWindTest.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala

- Handling null entry in ObjectHashMapAccessor during code generation
- added test in NorthWindTest itself
No
None
Detail log:
- Handling null entry in ObjectHashMapAccessor during code generation
- added test in NorthWindTest itself
- others are formatting changes as per our code style.
- refactored NW data population code a bit for external usage.

Fixing NPE in aggregation

---

cluster/src/dunit/scala/io/snappydata/externalstore/ColumnTableDUnitTest.scala
cluster/src/dunit/scala/org/apache/spark/sql/NorthWindDUnitTest.scala

* Unit Tests for SNAP-1188
* Exectued single test and it pass.Also executed precheckin and all test passed
(Does this change require an entry in ReleaseNotes.txt? If yes, has it been added to it?) No
[Store PR#129](https://github.com/SnappyDataInc/snappy-store/pull/129)

[SNAP-1188] Tests for SNAP-1188

---

core/src/test/scala/org/apache/spark/sql/store/CatalogConsistencyTest.scala

After changes SNAP-1199 the test  
> "Catalog is repaired after restart of the cluster" 
in CatalogConsistency scalatest is no longer valid as in scalatest we are not starting cluster. These test is properly covered in 
> CatalogConsistencyDunit.testCatalogRepairedWhenLeadRestarted.

Fix for SNAP-1214

---

build.gradle
examples/src/main/python/AirlineDataPythonApp.py
python/pyspark/sql/snappy/__init__.py
python/pyspark/sql/snappy/snappysession.py
python/pyspark/sql/snappy/tests.py
python/pyspark/streaming/snappy/context.py
python/pyspark/streaming/snappy/tests.py

a) Corrected Python objects to correctly use SparkSession APIs.
b) Changed build.gradle to point to correct PY4J library.
ran quickStart
ran python tests.
NA
NA

a) Corrected Python objects to correctly use SparkSession APIs.

---

cluster/src/test/scala/io/snappydata/benchmark/TPCHColumnPartitionedTable.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala

- now added a "isCollocatedJoin" methd that will walk through the tree to check cases of
collocated joins (including a collocated join result itself joining with another collocated table)
- also check for the sizes to check for the better side to broadcast
- changed Parquet writing in TPCHColumnPartitionedTable to use default compression since
for data on NFS cases, disk+network is going to be the bottleneck; also initialize the CREATE_PARQUET
flag based on test system property "snappydata.test.create_parquet"
precheckin, TPCH load testing, new tests to check for collocated/broadcast/hashjoin to be added subsequently
Notes about hashJoinSize and recommendations for broadcast and hashJoin limits
https://github.com/SnappyDataInc/spark/pull/35 created for overflow related issue which is …

[SNAP-1234] Check for collocated join before checking for broadcast

---

dtests/src/test/java/io/snappydata/hydra/clusterRestartWithPersistentRecovery.bt
dtests/src/test/java/io/snappydata/hydra/clusterRestartWithPersistentRecovery.conf
dtests/src/test/java/io/snappydata/hydra/ct/ct.bt
dtests/src/test/java/io/snappydata/hydra/ct/ctSplitModeCreateWithSparkApp.conf
dtests/src/test/java/io/snappydata/hydra/distJoin/distJoin.bt
dtests/src/test/scala/io/snappydata/hydra/ct/CTTestUtil.scala
dtests/src/test/scala/io/snappydata/hydra/ct/CreateAndLoadCTTablesApp.scala
dtests/src/test/scala/io/snappydata/hydra/ct/CreateAndLoadCTTablesJob.scala

Some minor test changes to : 
- Improve logging
- Modify location for data files.
- Some fixes for typos
Ran bts with the change.

Minor test changes

---

docs/aqp_aws.md
docs/install.md
docs/quickstart.md

* Edits to the pages pertaining to launching SnappyData on AWS including some urls.
NA
NA
NA

* Edits to the pages pertaining to launching SnappyData on AWS

---

cluster/src/main/scala/io/snappydata/gemxd/SnappyDataVersion.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardTab.scala

* Display SnappyData Product version on UI.
* Also display Underlying Spark Version in tooltip.
Tested Manually
https://github.com/SnappyDataInc/spark/pull/38

[SNAP-1244] Code changes for displaying product version details.

---

cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala

* External Spark Driver Node is displayed as CONNECTOR in Members List.
Tested Manually.
https://github.com/SnappyDataInc/snappy-store/pull/137

 [SNAP-1253]

---

core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

* Dashboard works fine even if all data servers goes down.
* Tested Manually.

Fixes for SNAP-1261 : Lead is alive but servers are dead. UI Dashboard fails to come up.

---

cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala

- List Spark connector mode driver in separate table on UI as a list of connectors.
- When the split driver (spark connector) stops, then the Connector entry will be removed from the list.
- Connectors table will be displayed only if at least one spark connector is connected and is live.
- Cluster status should not be changed based on Connector entries (i.e. No Warning when Spark connector stops/leaves cluster.
* Tested Manually.

SNAP-1293 : Code Change for displaying Spark connectors on UI

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala

* [SNAP-1308] Dunit test for SNAP-1308 to verify stats of column table in case of bulk insert from SplitMode
Test pass
https://github.com/SnappyDataInc/snappy-store/pull/139

[SNAP-1308] Dunit test for SNAP-1308 to verify stats of column table in case of bulk insert from SplitMode

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala

Issue is due to the callColumnBatch invocation which passes the encoders and cursor positions which
become too many for wide schema having a large number of columns.
Removed the encoder arguments (instead read from the class member variables) and pass cursor
arguments as an array if there are a large number of them (> 30)
insert passes that has been verified separately
NA
NA

[SNAP-1378] Fix for janino compilation failure in insert for large number of columns in table

---

cluster/src/test/scala/io/snappydata/cluster/StringAsClobTestSuite.scala
cluster/src/test/scala/io/snappydata/cluster/StringAsVarcharTestSuite.scala

Added test

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/DictionaryEncoding.scala

When switching to a big dictionary (having more than 32K items):
- pass the number of items encoded so far and not the dictionary size
- update the cursor with the new result
TPCH tests with 10GB of data (queries 4, 13, 21 pass with correct results)
NA
NA

[SNAP-1379] Fix the cursor handling when switching to BigDictionary in encoding

---

examples/src/main/scala/org/apache/spark/examples/snappydata/WorkingWithJson.scala
examples/src/main/scala/org/apache/spark/examples/snappydata/WorkingWithObjects.scala

Modified Object and json examples for simpler APIs.
Manual Testing
NA
NA

Modified Object and json examples for simpler APIs.

---

cluster/src/main/scala/org/apache/spark/sql/streaming/SnappyStreamingContextFactory.scala

Handled classloader incase of Streaming factory as well.
example suite
NA
NA

SNAP-1413 : Install Jar does not work with Streaming jobs

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala

For cases where limit was applied on query with column table, through jdbc route, each partition was overwriting results of earlier partition, that has been fixed. 
Will run precheckin
No
None

Fix for handling limit from JDBC

---

cluster/src/dunit/scala/io/snappydata/cluster/ExecutionEngineArbiterDUnitTest.scala

Tests for snap-1507
Store PR at https://github.com/SnappyDataInc/snappy-store/pull/174
https://github.com/SnappyDataInc/snappy-store/pull/174

Tests for snap-1507

---

cluster/src/dunit/scala/io/snappydata/cluster/ValidateMVCCDUnitTest.scala

* ValidateMVCCDunit Test changes to properly elevate exception from VM
* Tested Manually by executing this test
* Precheckin in progress
NA
https://github.com/SnappyDataInc/snappy-store/pull/183

[SNAP-1563] ValidateMVCCDunit Test changes to properly elevate exception from VM

---

core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

- Handle exception and log into log file.
- Tested Manually

SNAP-1494: Dashboard shows an exception stack trace when a server goes down

---

dtests/src/test/java/io/snappydata/hydra/ct/ct.bt
dtests/src/test/scala/io/snappydata/hydra/SnappyTestUtils.scala
dtests/src/test/scala/io/snappydata/hydra/TestUtil.scala

- Modifying test code to use SnappyTestUtils.writeToFile method for writing query result to csv.
- Changed default persistence mode to 'sync'.
Ran ct.bt

Fixing FileNotFoundException occured while running sparkApp for query validation

---

cluster/sbin/snappy-nodes.sh

* Changes in launch script to pick proper locator hostname and arguments
* Changes in launch script for starting multiple locators with -start-locator arguments
* Added extra regex for checking if user has defined any custom ports for locators.
* Extra regex added for checking if user has not created conf files. 
Manually
N/A
N/A

changes in launch script to pick proper locator hostname

---

cluster/src/dunit/scala/io/snappydata/cluster/ValidateMVCCDUnitTest.scala

* Test fixes for validateMVCCDunit test and added logs
* Manually execute ValidateMVCCDunittest
NA
NA

Test fixes for validateMVCCDunit test and added logs

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala

This is to ensure that at the server, we cleanup the txContext

Issue commit even if the tx is already committed

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java

- Added support for starting and stopping spark cluster from any node in multihost environment
Verified the changes by running northWind bt in multiHost environment
NA
No

Added support for starting and stopping spark cluster from any node in multihost environment

---

cluster/src/test/scala/io/snappydata/cluster/QueryRoutingSingleNodeSuite.scala
core/src/main/java/io/snappydata/impl/SnappyHiveCatalog.java
core/src/main/scala/org/apache/spark/sql/hive/HiveClientUtil.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala

Fix for SNAP-1671: 'show tables in app' query doesnot list sample table.
Fix for SNAP-1655: support for boolean in row tables
Precheckin done.
@soubhik-c  Please confirm testcase for 1655 is working fine.
@spillai14  Please confirm testcase for 1671 is working fine.
No
https://github.com/SnappyDataInc/snappy-store/pull/214

    Patch from Sumedh:

---

cluster/src/test/scala/io/snappydata/cluster/QueryRoutingSingleNodeSuite.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala

While passing value to XD, it should converted from catalyst type to scala type. This was missed for partition pruning changes and that has been corrected.
precheckin.
No
No

SNAP-1737: 

---

core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala

Corrected the scaladoc examples in SnappySession.
clean buildAll
NA
NA

Corrected the scaladoc examples in SnappySession.

---

core/src/main/scala/org/apache/spark/sql/SnappyContext.scala

Added log statements so that it will be easier to find the cluster mode by looking at the logs.
precheckin
Not applicable
Not applicable

Changes for SNAP-1678

---

cluster/src/dunit/scala/org/apache/spark/sql/udf/UserDefinedFunctionsDUnitTest.scala

Disabling test which fails intermittently
ran  standalone test
NA
NA

[SNAP-1681] Disabling test which fails intermittently.

---

core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala

Test for SNAP-1345
This is the test.
None.
No.

simple test to reproduce SNAP-1345

---

cluster/src/dunit/scala/org/apache/spark/memory/SnappyUnifiedMemoryManagerDUnitTest.scala

modified test to start recovery after startup by modifying default recovery delay.
Adde more logs for future failures.
pre-checkin
NA
NA

modified test to start recovery after startup.

---

dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/startUp/ddlOpAfterLocatorStop_clusterRestart.inc
dtests/src/test/java/io/snappydata/hydra/startUp/ddlOpLocatorHA.inc

- Added fix for SNAP-1765
- Fixed minor issue in startUp tests
Verified the changes by running failing tests.
NA
No

Fix for SNAP-1765

---

cluster/src/dunit/scala/org/apache/spark/memory/SnappyUnifiedMemoryManagerDUnitTest.scala

Changed test to reset memorymanager to clear static variable.
unit test
NA
NA

Changed test to reset memorymanager to clear static variable.

---

cluster/sbin/snappy-status-all.sh

Part of fix for SNAP-352 
Passing the extra args passed to status-all script to internal launcher invocations.
Manual
None.
No.

Part of fix for SNAP-352 

---

cluster/src/dunit/scala/io/snappydata/cluster/DDLRoutingDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/test/scala/org/apache/spark/sql/store/RowTableTest.scala

- Fix for SNAP-1825, SNAP-1818
- DDL routing changes 
- ALTER TABLE made column as optional field
- GW/AEL DDLs routed to store directly (others working correctly)
- Added tests 
clean precheckin 
None
- https://github.com/SnappyDataInc/snappy-store/pull/257

DDL routing changes 

---

core/src/main/scala/org/apache/spark/sql/catalyst/expressions/ParamLiteral.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

* Added generated code for ParamLiteral case statement including NullType
precheckin 
No
No

SNAP-1894 Codegen issue for query with case in predicate expression

---

cluster/src/test/scala/io/snappydata/cluster/QueryRoutingSingleNodeSuite.scala

Added test. Routed put into query should return actual number of rows inserted.
Precheckin
No
https://github.com/SnappyDataInc/snappy-store/pull/279

[SNAP-1451] 

---

core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnBatch.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala

Register task listener as soon as conn is taken

[SNAP-1915] Register task listener as soon as conn is taken

---

cluster/bin/snappy-job.sh

Added an option to specify the streaming batch interval.
Before this change, there was no way to change streaming job batch interval. 
One can specify the batch interval as below
`bin/snappy-job.sh submit --lead localhost:8090 --app-name appname --class  appclass --app-jar appjar --conf logFileName=demo.txt --stream --batch-interval 4000`
preccheckin
Will require a doc change.
NA

[SNAP_1948] Added an option to specify streaming batch interval.

---

cluster/sbin/snappy-lead.sh
cluster/sbin/snappy-server.sh
cluster/src/main/scala/io/snappydata/gemxd/SnappyDataVersion.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
cluster/src/main/scala/org/apache/spark/executor/SnappyExecutor.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/ColumnCacheBenchmark.scala
cluster/src/test/scala/org/apache/spark/sql/execution/benchmark/TAQTest.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/JDBCAppendableRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala

SNAP-1660 Remove password from product logging
Also, add enterprise checks before loading AQP and Off-heap modules.
Manually tested.
NA
https://github.com/SnappyDataInc/snappy-store/pull/283

SNAP-1660 Remove password from product logging

---

examples/src/main/python/KMeansWeather.py
examples/src/test/scala/io/snappydata/quickstart/ExampleTestSuite.scala

File from Sid. 
A python script example to compute KMeans from weather data. This uses SnappySession as entry point. 
example suite
NA

[SNAP-1995] Added a pyhon KMeans example

---

cluster/src/test/scala/org/apache/spark/sql/MiscTest.scala

There was an issue with 'with' clause. That was fixed in the aqp branch. Adding a test here for the same. 
Manual. Precheckin .

Added test for With Clause Fix

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala

Added a test to check that internal column table does not shows up in metadat queries
added a test
None.
No

Part of SNAP-1938

---

core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoinExec.scala
core/src/test/scala/org/apache/spark/sql/streaming/SnappyStreamingSuite.scala

- HashJoinExec's inputRDDs are computed on each CQ execution.
- Added test 
precheckin 
No
None

SNAP-2003 stream to big table join CQ incorrect result

---

build.gradle

Adding copying of libgemfire*.so to product and output directories.
Also reduced the parallel forks for unit tests.
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/313

Copy libgemfire*.so to product directory

---

build.gradle
cluster/build.gradle
cluster/src/main/scala/io/snappydata/gemxd/ClusterCallbacksImpl.scala
cluster/src/main/scala/io/snappydata/gemxd/SnappyDataVersion.scala
core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

* Update build id based on property enablePublish.
* More details on another PR.
precheckin in-progress
NA
https://github.com/SnappyDataInc/snappy-aqp/pull/160
https://github.com/SnappyDataInc/snappy-store/pull/308

ENT-3 Update build id based on a version property.

---

core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

Fixed a parser issue where AS can be optional in namedExpression rule. q77 of tpcds was failing.
added a unit test.
None.
No

SNAP-2031 -- q77 of tpcds was failing

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala

Augmented an existing test for SNAP-2037
NA
No.
https://github.com/SnappyDataInc/snappy-store/pull/318

Augmented an existing test for SNAP-2037

---

docs/howto/spark_installation_using_smart_connector.md
examples/src/main/scala/org/apache/spark/examples/snappydata/SmartConnectorExample.scala
examples/src/test/scala/io/snappydata/quickstart/ExampleTestSuite.scala

Updated smart connector how to as requested in the JIRA

Updated smart connector how to as requested in the JIRA

---

cluster/src/main/scala/io/snappydata/cluster/ExecutorInitiator.scala
cluster/src/main/scala/org/apache/spark/executor/SnappyExecutor.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowFormatScanRDD.scala
core/src/test/resources/log4j.properties

- added ThreadFactory to SnappyExecutor to cleanup thread artifacts on
close with ConnectionTable.releaseThreadsSockets() as done by other pool threads
- updated snapshotTxState calls as per the changes in store
precheckin with store
NA
https://github.com/SnappyDataInc/snappy-store/pull/327

[SNAP-2068] cleanup open transactions and TXContexts

---

docs/additional_files/additional_docs.md
docs/aqp_aws.md
docs/configuration.md
docs/configuring_cluster/configuring_cluster.md
docs/configuring_cluster/property_description.md
docs/howto/use_apache_zeppelin_with_snappydata.md
docs/install.md
docs/install/install_on_premise.md
docs/install/setting_up_cluster_on_amazon_web_services.md
docs/isight/quick_start_steps.md
docs/troubleshooting/troubleshooting.md
mkdocs.yml

Updated documentation for 1.0.0

---

cluster/src/dunit/scala/io/snappydata/cluster/SetIsolationDUnitTest.scala

Converted the scenario given in SNAP-2082 to a dunit test.
Above test was run with the code changes on store of branch SNAP-2082
No

Test for put into on replicated table ( SNAP-2082 )

---

cluster/conf/log4j.properties.template
cluster/src/test/resources/log4j.properties
core/src/main/scala/org/apache/spark/Logging.scala
core/src/test/resources/log4j.properties

change to the new Layout which appends threadID in templates and test log4j properties
manual
NA
https://github.com/SnappyDataInc/snappy-store/pull/335

update PatternLayout in templates/tests

---

cluster/sbin/snappy-config.sh
cluster/sbin/snappy-lead.sh
cluster/sbin/snappy-nodes.sh
cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerTestBase.scala
cluster/src/dunit/scala/io/snappydata/cluster/DDLRoutingDUnitTest.scala
cluster/src/test/scala/org/apache/spark/memory/SnappyLocalIndexAccountingSuite.scala
core/src/test/scala/io/snappydata/SnappyFunSuite.scala
core/src/test/scala/io/snappydata/SnappyTestRunner.scala
dunit/src/main/java/io/snappydata/test/dunit/DistributedTestBase.java
dunit/src/main/java/io/snappydata/test/dunit/standalone/DUnitLauncher.java
examples/src/test/scala/io/snappydata/quickstart/ExampleTestSuite.scala

- get the public hostname in AWS environment and set SPARK_PUBLIC_DNS to it
- set bind-address, SPARK_LOCAL_IP and SPARK_PUBLIC_DNS explicitly to localhost for a
localhost-only cluster
- set above properties to localhost in unit tests too
precheckin; manual checks in AWS and datacentre networks
Mention about the default set for SPARK_PUBLIC_DNS in AWS
https://github.com/SnappyDataInc/snappy-store/pull/343

[SNAP-2116] auto-configuration for AWS and local clusters

---

README.md

Download link contained an extra slash

Fixed a slash in the link

---

core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyContext.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala
core/src/test/scala/org/apache/spark/sql/store/DisableTokenizationTest.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

Corrected some perf mistakes pointed in review comment of SNAP-2125
https://github.com/SnappyDataInc/snappydata/pull/923
Same test passed.
Need to add newly added properties in documentation.
https://github.com/SnappyDataInc/snappydata/pull/923

perf improvements over SNAP-2125

---

docs/howto/load_data_into_snappydata_tables.md
docs/programming_guide/tables_in_snappydata.md

Just a couple small documentation fixes.
NA
No
Nope.

Docs progguide tables syntax fix

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterManagerTestBase.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/ColumnEncoding.scala
core/src/test/scala/io/snappydata/core/LocalTestData.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

- test to check that JDBC query execution returns a count for such routed DMLs
- enabled spark.memory.debugFill for unit tests to detect many cases of incorrect memory
read/write
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/359

[SNAP-2156] added test for the case

---

cluster/src/test/scala/org/apache/spark/sql/execution/SnappyTableMutableAPISuite.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/internal/ColumnTableBulkOps.scala

Materialized cache for intermediate inner join in a put operation.
limited scala tests using put operation & CDC connector tests
NA
NA

Explicit Action for put innerjoin cache.

---

cluster/src/test/scala/org/apache/spark/sql/execution/SnappyTableMutableAPISuite.scala
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyImplicits.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/internal/ColumnTableBulkOps.scala

Fixed putinto inner join cache perf and related issues.
prechecking
NA
https://github.com/SnappyDataInc/spark/pull/92

Fixed putinto inner join cache perf and related issues.

---

cluster/src/test/scala/org/apache/spark/sql/execution/SnappyTableMutableAPISuite.scala
core/src/main/scala/org/apache/spark/sql/execution/ObjectHashMapAccessor.scala

Condition in exist was incorrect.
Corrected the logic of existence join, which was looking for null values earlier. 
Unit test added.
NA
Na

Condition in exist was incorrect.

---

cluster/src/test/scala/org/apache/spark/sql/store/SnappyUDFTest.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala

If a function is created the very first thing after creating the schema, it fails as the schema is
not registered in Hive catalog. In table creation we handle the catalog db creation if the db is not present.
Similar handling added for functions.
precheckin
na
NA

[SNAP-2241] Handled catalog database creation.

---

cluster/src/main/scala/io/snappydata/gemxd/ClusterCallbacksImpl.scala
cluster/src/main/scala/io/snappydata/gemxd/SnappyDataVersion.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala

- added task cancellation checks at the start of new batch in ColumnTableScan
- also when putting a batch in JDBCSourceAsColumnarStore
- close some dangling file handles
precheckin in progress
NA
NA

[SNAP-2338] check for task cancellation for each batch

---

core/src/test/scala/org/apache/spark/sql/store/ViewTest.scala

added bug test for SNAP-2342

---

cluster/src/dunit/scala/io/snappydata/cluster/SnappySecureJob.scala
cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEntry.scala

Minor formatting/doc changes and updated store link.
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/389

[GITHUB-982] negative bucket size with eviction

---

core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

- Setting correct Table Type after collecting all table stats in lead node.
This fixes problem of converting table type from Column to Row when there is column store drop due to some reasons.
- Tested with hack in code.
- None
- None

Fixes for SNAP-2382: Column table mysteriously changes to Row table on dashboard after LME in data serever

---

core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala

- Adding fixes for possible NullPointerException.
- Tested manually and with hack in code.
- None
- Store: https://github.com/SnappyDataInc/snappy-store/pull/402

Fixes for SNAP-2390:

---

cluster/src/main/scala/org/apache/spark/status/api/v1/ClusterDetails.scala
cluster/src/main/scala/org/apache/spark/status/api/v1/MemberDetails.scala
cluster/src/main/scala/org/apache/spark/status/api/v1/snappyapi.scala
cluster/src/main/scala/org/apache/spark/ui/SnappyDashboardPage.scala

- Adding CPU cores details in the ClusterDetails and MemberDetails.
- HTML code changes for displaying, CPU cores used in cluster, on Dashboard page.
- Tested Manually
- Yes
- Spark: https://github.com/SnappyDataInc/spark/pull/109
- Store: https://github.com/SnappyDataInc/snappy-store/pull/401

Code changes for SNAP-2144:

---

cluster/src/test/scala/org/apache/spark/sql/MiscTest.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala

currentschema should be considered for plan caching
Added a unit test
No
None

Fix to SNAP-2438

---

core/src/main/scala/io/snappydata/SnappyTableStatsProviderService.scala
core/src/main/scala/io/snappydata/TableStatsProviderService.scala

- To speed up the dashboard data auto-refresh, removing unnecessary empty checks on table stats info and external table stats info.
- Exception trace is logged at debug level if exception occurs while collecting Table Statistics.
- Manually
- None
- None

Fixes for SNAP-2400:

---

cluster/src/test/scala/io/snappydata/cluster/PreparedQueryRoutingSingleNodeSuite.scala

Unit test for reproducing Snap 2446
NA
Looks at the corresponding store PR
https://github.com/SnappyDataInc/snappy-store/pull/410

Unit test for reproducing Snap 2446

---

compatibilityTests/src/test/scala/org/apache/spark/sql/SnappyTableScanSuite.scala

Earlier fixes done to [SNAP-2307 ](https://jira.snappydata.io/browse/SNAP-2307) are undone hence fixing them in the way suggested by @rishitesh 
Tested SnappyTableScanSuite and TableScanSuite 
no
no

fixes for SNAP-2307  in SnappyTableScanSuite

---

core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala

Changes to split the view definition string & store it as split properties in the Map, to fix the issue of view string size exceeding 37200 chars.

Bigviewbug

---

core/src/main/scala/org/apache/spark/sql/execution/joins/HashJoinExec.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappyStoreHiveCatalog.scala
core/src/test/scala/org/apache/spark/sql/store/ColumnTableTest.scala

1) Wrapped replicated joins in DelegateRDD. 
Without it, the buildRDDs were not visible in dependency graphs. 
2) Some formatting changes.
precheckin
NA
NA

[SNAP-2483]Wrapped replicated joins in DelegateRDD

---

core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala

disabling local hash joins

---

cluster/sbin/snappy-start-all.sh
cluster/sbin/snappy-status-all.sh
cluster/sbin/snappy-stop-all.sh
core/src/main/scala/io/snappydata/Literals.scala
core/src/main/scala/org/apache/spark/sql/SnappyBaseParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/SnappyStrategies.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatEntry.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/ColumnFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala
core/src/main/scala/org/apache/spark/sql/row/JDBCMutableRelation.scala
core/src/main/scala/org/apache/spark/sql/sources/StoreStrategy.scala
core/src/main/scala/org/apache/spark/sql/sources/interfaces.scala
core/src/main/scala/org/apache/spark/sql/store/CompressionUtils.scala
core/src/test/scala/org/apache/spark/sql/store/TokenizationTest.scala

- add a wrapper LogicalPlan to carry the query hints for a plan
- analyze above in Snappy join strategies to force hash or broadcast join
in progress
Note about the query hint
NA

[SNAP-2571] add query hint to force join type

---

cluster/src/dunit/scala/io/snappydata/cluster/SparkJDBCDUnitTest.scala
cluster/src/dunit/scala/io/snappydata/cluster/SparkJDBCTestJob.scala
cluster/src/test/scala/io/snappydata/cluster/JDBCConnectionPoolTestSuite.scala

Added a Scala Tests and DUnit Test for the JDBC Client Pool Driver.
- By using scala test, covered the functional JDBC test cases
- By using DUnit test, covered the spark-submit scenario
This only a test patch.
https://github.com/SnappyDataInc/snappy-store/pull/428

Test Cases for the JDBC Pool Driver.

---

build.gradle
cluster/src/dunit/scala/io/snappydata/cluster/SnappySecureJob.scala
cluster/src/main/scala/org/apache/spark/sql/SnappySessionFactory.scala

* Cleanup the jobconfig before invoking runSnappyJob()
DUnit passes.
NA
NA

* Cleanup the jobconfig before invoking runSnappyJob()

---

examples/src/main/scala/org/apache/spark/examples/snappydata/StructuredStreamingCDCExample.scala
examples/src/main/scala/org/apache/spark/examples/snappydata/StructuredStreamingExample.scala
examples/src/main/scala/org/apache/spark/examples/snappydata/StructuredStreamingWithSnappySink.scala
examples/src/main/scala/org/apache/spark/examples/snappydata/StructuredStreamingWithSnappysink.scala

Created a new class for snappysink example instead of replacing existing structured streaming example.
No code changes involved.  Have manually executed the added/modified examples.

Created new class for snappysink example instead of replacing existing

---

core/src/main/scala/org/apache/spark/sql/execution/ddl.scala

Putinto fixes

---

cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/catalyst/expressions/ParamLiteral.scala

RefParamLiteral of RefParamLiteral was being created so referenceEquals was returning false.
Correct the search to ensure that RefParamLiterals are skipped and also added an assertion that
RefParamLiteral should never wrap another RefParamLiteral.
Added a test with views to check above.

RefParamLiteral being checked for equality against another RefParamLiteral

---

cluster/src/test/scala/org/apache/spark/sql/store/SecurityBugTest.scala

Added bug test for SNAP-2827
The fix is in store branch
[store pr](https://github.com/SnappyDataInc/snappy-store/pull/462)

added bug test for SNAP-2827

---

core/src/main/scala/org/apache/spark/sql/streaming/SnappySinkCallback.scala

those operations which are required
Earlier we were counting only delete and update events and skipping both the operations if no update or delete events exists. Insert job was submitted irrespective of the presence of insert events.
With this change, we are counting events for all event types and performing the operation only if respective events are present in the incoming batch.
Manual testing, Existing sink tests passing, Some performance tests
Following are the readings for the time taken by count job for older and newer approach:
- 50k 2 seconds
- 100k 2 seconds
- 1m 11 seconds
- 50k 1 second
- 100k 5 seconds
- 1m 12 seconds

SNAP-2931 - counting each event type separately and submitting only

---

cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala

Fixes for limit query issues (from Suemdh)
- Limit query on external tables resulted in scan of all partitions when result could be returned by scanning just 1 partition
- Excpetion "parkSQLExecuteImpl: getPartitionData() block rdd_30_0 not found" was thrown for multi-partition limit query
Unit tests added
precheckin
NA
NA

Fixes for limit query

---

cluster/src/dunit/scala/io/snappydata/cluster/ClusterMgrDUnitTest.scala

This PR contains a unit test
Unit tests, precheckin

Changes to wrap non-fatal OOME from Spark layer in LowMemoryException

---

examples/src/main/scala/org/apache/spark/examples/snappydata/StreamingExample.scala

example code cleanup
Run the example and it is running without change in behaviour

example code cleanup

---

cluster/src/main/scala/io/snappydata/impl/LeadImpl.scala
core/src/main/scala/io/snappydata/sql/catalog/SmartConnectorHelper.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnTableScan.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/StoreCallbacksImpl.scala
encoders/src/main/scala/org/apache/spark/sql/collection/SharedUtils.scala
encoders/src/main/scala/org/apache/spark/sql/execution/columnar/encoding/DictionaryEncoding.scala

Issue was incorrect number of columns being determined in ColumnTableScan for the base table
due to output projection not having the extra virtual columns projected.
- use relation schema to determine put/update case rather than output projection in ColumnTableScan
- removed duplicate methods across SharedUtils and Utils
precheckin
NA
NA

[SNAP-2975] fix SEGV in putInto

---

build.gradle
release/preInstallDeb.sh
release/preInstallRpm.sh

- Bumped up versions as below:
snappydata 1.0.2.1   ->   1.1.0
snappy-store 1.6.2.1   ->   1.6.3
spark 2.1.1.4   ->   2.1.1.5
spark-jobserver 0.6.2.8   ->   0.6.2.9
zeppelin interpreter 0.7.3.4   ->   0.7.3.5
- Updated archive names and org names.
- Changes in submodules (store, spark, aqp and snappy-connectors) are similar but minor ones.
Basic testing with cluster launch and CREATE DDL
NA
Changes in build.gradle of other repos. Will be added soon.

* Versioning related changes for upcoming 1.1.0 release.

---

build.gradle
cluster/bin/snappy
encoders/build.gradle

Updated some metainfo in prep for 1.1.0 release.
Also contains fix for SNAP-2854 in cluster/bin/snappy.
./gradlew cleanAll buildAll distProduct
If launching in AWS and the EC2 instance has multiple public IP addresses, the lead node/driver is bound to the first one.
NA

Version updates 1.1.0

---

docs/connectors/gemfire_connector.md
docs/connectors/jdbc_streaming_connector.md
docs/howto/concurrent_apache_zeppelin_access_to_secure_snappydata.md
docs/howto/connect_oss_vis_client_tools.md
docs/howto/connect_using_jdbc_driver.md
docs/howto/using_snappydata_for_any_spark_dist.md
docs/install.md
docs/install/setting_up_cluster_on_amazon_web_services.md
docs/kubernetes.md
docs/programming_guide/spark_jdbc_connector.md
docs/quickstart/getting_started_on_kubernetes.md
docs/quickstart/getting_started_with_docker_image.md

* Updates to Docker, k8s and AMI content
* Doc version changes 
NA
NA
NA

Doc version changes 02

---

README.md
docs/affinity_modes/connector_mode.md
docs/affinity_modes/local_mode.md
docs/configuring_cluster/configuring_cluster.md
docs/connectors/deployment_dependency_jar.md
docs/connectors/gemfire_connector.md
docs/connectors/jdbc_streaming_connector.md
docs/howto/connect_jdbc_client_pool_driver.md
docs/howto/connect_oss_vis_client_tools.md
docs/howto/connect_using_jdbc_driver.md
docs/howto/connect_using_odbc_driver.md
docs/howto/run_spark_job_inside_cluster.md
docs/howto/spark_installation_using_smart_connector.md
docs/howto/use_apache_zeppelin_with_snappydata.md
docs/install.md
docs/install/setting_up_cluster_on_amazon_web_services.md
docs/programming_guide/snappydata_jobs.md
docs/programming_guide/using_snappydata_shell.md
docs/quickstart/getting_started_by_installing_snappydata_on-premise.md
docs/quickstart/getting_started_with_your_spark_distribution.md
docs/quickstart/performance_apache_spark.md
docs/reference/command_line_utilities/store-version.md
docs/reference/interactive_commands/connect_client.md
docs/security/specify_encrypt_passwords_conf_client.md
docs/setting_up_odbc_driver-tableau_desktop.md

* Updated versions for 1.1.0 release
NA
NA
NA

* Docs change: Updated versions for 1.1.0 release

---

cluster/src/dunit/scala/io/snappydata/cluster/PreparedQueryRoutingDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLPrepareImpl.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/internal/SnappySessionState.scala

The PromoteString rule is removed from the analyzer phase. It was intended to be removed
but the questionMarkCounter additional filter was sometimes causing the
rule to not get excluded. Since this is specific to prepare phase so removing it completely is not an issue.
Added a multi thread dunit test.

Fix of bug SNAP-2644

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLPrepareImpl.scala
cluster/src/test/scala/io/snappydata/cluster/QueryRoutingSingleNodeSuite.scala
cluster/src/test/scala/org/apache/spark/sql/SQLFunctionsTestSuite.scala
core/src/main/scala/org/apache/spark/sql/SnappyParser.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala

Added code for handling table with different schema name other than default schema APP for PUT INTO VALUES syntax of column table
Added scala tests and dunit test
NA
None

Added fix and test for SNAP-3038

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala
core/src/main/scala/org/apache/spark/sql/collection/Utils.scala
core/src/main/scala/org/apache/spark/sql/execution/TableExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ColumnInsertExec.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/impl/JDBCSourceAsColumnarStore.scala
core/src/main/scala/org/apache/spark/sql/execution/row/RowExec.scala

Added check for schema version when insert/update/delete operation are done from smart connector mode. On schema version change, now CatalogStaleException will be thrown and cached catalog tables will be cleared so that schema is fetched from embedded side.
Added new unit tests
New unit tests
precheckin

Snap 2228 fix

---

cluster/src/dunit/scala/io/snappydata/cluster/SplitSnappyClusterDUnitTest.scala

* Undeploy the deployed packages after the test, as it was affecting other tests when run together.
Ran dunit tests from cluster module, which was affected.

Improving the unit test for the [SNAP-2355]

---

cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala

Unit tests for SNAP-2765 (https://github.com/SnappyDataInc/snappy-store/pull/487)
precheckin
NA
https://github.com/SnappyDataInc/snappy-store/pull/487

Test for SNAP-2765

---

core/src/test/scala/io/snappydata/CommandLineToolsSuite.scala

Added automated test for run command
NA
NA
this PR linked to the [https://github.com/SnappyDataInc/snappy-store/pull/490](url)

Added automated test for run command

---

cluster/src/dunit/scala/io/snappydata/cluster/QueryRoutingDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala

minor assert message corrections
n/a
no
none

Snap 1327: minor assert message corrections

---

dtests/src/resources/scripts/streaming_sink/createTempTableForStreaming.sql
dtests/src/test/java/io/snappydata/hydra/adAnalytics/SnappyAdAnalyticsTest.java
dtests/src/test/java/io/snappydata/hydra/cluster/SnappyTest.java
dtests/src/test/java/io/snappydata/hydra/streaming_sink/streamingAgg/startClusterDualModeAgg.inc
dtests/src/test/scala/io/snappydata/hydra/streaming_sink/CreateTableForJoinJob.scala
dtests/src/test/scala/io/snappydata/hydra/streaming_sink/StringMessageProducer.scala

- Adding method to have stack dump for spark driver processes, in case of hang.
- Changing the table type for snappy table in streaming app to partitioned row table.
- Minor fixes in the test
Ran streaming bt, dmlOps.bt
N/A
N/a

Few test changes and minor fixes.

---

build.gradle
publish-site.sh

Add a gradle task "buildSqlFuncDocs" for the same purpose.
Manually
None
https://github.com/SnappyDataInc/spark/pull/166

Generate docs for built-in spark-supported sql functions

---

build.gradle
publish-site.sh

* Name change of the target directory.
Manually

Sql function docs

---

cluster/src/test/scala/io/snappydata/cluster/PreparedQueryRoutingSingleNodeSuite.scala
cluster/src/test/scala/org/apache/spark/sql/SQLFunctionsTestSuite.scala
cluster/src/test/scala/org/apache/spark/sql/kafka010/SnappyStructuredKafkaSuite.scala
cluster/src/test/scala/org/apache/spark/sql/store/ColumnUpdateDeleteTest.scala
cluster/src/test/scala/org/apache/spark/sql/store/SHAByteBufferTest.scala
compatibilityTests/src/test/scala/org/apache/spark/sql/test/SharedSnappySessionContext.scala
core/src/test/scala/io/snappydata/core/LocalTestData.scala

Modified the tests to disable codegenfallback as per need to test optimized sha code

Tests enhancements

---

cluster/src/dunit/scala/io/snappydata/cluster/PreparedQueryRoutingDUnitTest.scala

Refer to store side PR (https://github.com/SnappyDataInc/snappy-store/pull/521) opened by @kneeraj for fix.
Unit test
NA
https://github.com/SnappyDataInc/snappy-store/pull/521

Test for GitHub issue 1436

---

docs/configuring_cluster/configuring_cluster.md
docs/monitoring/monitoring.md
docs/reference/sql_reference/drop-schema.md

Edits to History Server topic. 
NA
NA
NA

Community docv1.1.1 temp2

---

core/src/main/scala/io/snappydata/sql/catalog/impl/StoreHiveCatalog.scala

* Added missing condition.
* Extended existing test.
Done manual testing. No relevant errors found in precheckin.
None
None

Fixing SNAP-3185

---

cluster/sbin/snappy-start-all.sh
cluster/sbin/snappy-status-all.sh

Added code to exit from snappy-start-all.sh and snappy-status-all.sh scripts on invalid argument input.
Manual
NA
NA

Added code to exit on invalid argument input

---

cluster/src/test/scala/org/apache/spark/sql/store/SHAByteBufferTest.scala
core/src/main/scala/org/apache/spark/sql/execution/SHAMapAccessor.scala
core/src/main/scala/org/apache/spark/sql/execution/aggregate/SnappyHashAggregateExec.scala

Snap 3149 1

---

core/src/main/scala/org/apache/spark/sql/execution/oplog/impl/OpLogRdd.scala

- Column decoder doesnt keep reference to the direct bytebuffer  which is resulting in hs error after reading a few records. 
- Changes are added to keep reference of the buffer till we are done reading
Ran tests of the modules individually
No
None

SNAP-3225 fix for hs error in data extractor

---

core/src/main/scala/io/snappydata/recovery/RecoveryService.scala
core/src/main/scala/org/apache/spark/sql/execution/oplog/impl/OpLogFormatRelation.scala
core/src/main/scala/org/apache/spark/sql/execution/oplog/impl/OpLogRdd.scala

catalog table field in some cases is observed to be in upper case which was resulting in NPE. converting to lower to handle
ran PrimaryDUnitRecoveryTest
no
none

In DataExtractor converting catalog table field names to lower

---

cluster/src/dunit/scala/io/snappydata/cluster/PrimaryDUnitRecoveryTest.scala
core/src/main/scala/org/apache/spark/sql/execution/oplog/impl/OpLogRdd.scala

* Adding support for CHAR data type
* Added tests and minor refactoring
Manually and running relevant tests.

[SNAP-3246] - 

---

core/src/main/scala/org/apache/spark/sql/internal/SnappySessionCatalog.scala

* capturing create database statement required for EXPORT_DDLS procedure
* handling creation of user schemas in recovery helper scripts
Ran precheckin
no
no

Snap 3289 capture create database statement

---

cluster/src/main/scala/io/snappydata/ToolsCallbackImpl.scala
cluster/src/main/scala/io/snappydata/remote/interpreter/SnappyInterpreterExecute.scala
core/src/main/scala/io/snappydata/ToolsCallback.scala
core/src/main/scala/org/apache/spark/sql/SnappyDDLParser.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/execution/ddl.scala

returning a proper dataframe in all cases.
precheckin and manual testing
yes
No.

Changes to make exec scala work from hivethriftserver too.

---

cluster/src/main/scala/io/snappydata/remote/interpreter/RemoteInterpreterStateHolder.scala
cluster/src/main/scala/io/snappydata/tools/SnappyUtilLauncher.scala
core/src/test/scala/io/snappydata/CommandLineToolsSuite.scala

- Changed the default snappysession name from 'snappy' to 'snappysession'
- An error in interpreting a line now results in a runtime exception.
precheckin, manual
No.
None.

A couple of minor modifications in exec scala feature.

---

cluster/src/dunit/scala/io/snappydata/externalstore/JDBCPreparedStatementDUnitTest.scala
cluster/src/main/scala/io/snappydata/gemxd/ClusterCallbacksImpl.scala
cluster/src/main/scala/io/snappydata/gemxd/SparkSQLExecuteImpl.scala
core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala
core/src/main/scala/org/apache/spark/sql/hive/SnappySessionState.scala

Changes to support query cancellation using JDBC.
- added new test
- precheckin clean
https://github.com/SnappyDataInc/snappy-store/pull/551

[SDENT-175] Support for cancelling query via JDBC

---

docs/howto/deploy_tcdb_aws_marketplace.md
docs/install/setting_up_cluster_on_amazon_web_services.md

Enterprise docv1.2.0 changes to include AWS Marketplace offering
NA
NA
NA

Enterprise docv1.2.0 changes to include AWS Marketplace offering

---

cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala

* Fix for SDENT-187, by handling EqualTo(Attribute, Attribute) case.
* Added a testcase.
precheckin running
NA
NA

* Fix for SDENT-187, by handling EqualTo(Attribute, Attribute) case.

---

cluster/src/dunit/scala/io/snappydata/externalstore/JDBCMetadataCaseDUnitTest.scala

* Added a testcase for SDENT-194
Ran the affected testcases
NA
https://github.com/TIBCOSoftware/snappy-store/pull/557

* Added a testcase for SDENT-194

---

cluster/src/test/scala/org/apache/spark/sql/store/BugTest.scala
core/src/main/scala/org/apache/spark/sql/execution/columnar/ExternalStoreUtils.scala

Handle comparisons other than EqualTo for select query on a row table with primary key.
precheckin
NA
NA

* Second fix for SDENT-187.

---

docs/Data/data_formats.md
docs/Data/external_hive_support.md
docs/additional_files/open_source_components.md
docs/architecture/core_components.md
docs/architecture/data_ingestion_pipeline.md
docs/best_practices/important_settings.md
docs/best_practices/memory_management.md
docs/best_practices/setup_cluster.md
docs/configuring_cluster/properties.md
docs/configuring_cluster/property_description.md
docs/configuring_cluster/property_details.md
docs/connectors/tdv.md
docs/howto.md
docs/howto/concurrent_apache_zeppelin_access_to_secure_snappydata.md
docs/howto/connect_jdbc_client_pool_driver.md
docs/howto/connect_using_jdbc_driver.md
docs/howto/connecttibcodv.md
docs/howto/use_synopsis_data_engine_to_run_approximate_queries.md
docs/new_features.md
docs/reference/configuration_parameters/config_parameters.md
docs/reference/configuration_parameters/load-balance.md
docs/reference/configuration_parameters/statistic-sample-rate.md
docs/reference/misc/passwordless_ssh.md
docs/reference/sql_reference/exec-scala.md
docs/reference/sql_reference/select.md
docs/troubleshooting/collect_debug_artifacts.md

Added new files and few docuentation changes

[SDENT-196] Added new files and few docuentation changes

---

core/src/main/scala/org/apache/spark/sql/CachedDataFrame.scala
core/src/main/scala/org/apache/spark/sql/SnappySession.scala

Added fix for SDENT-199
Findings of precheckin run :
Only three new failures in precheckin but those are seen due change in version  of hadoop client libraries.
Name of the tests which are failed in spark side precheckin run:-
1. MasterSuite
2. JavaDataFrameSuite
3. JavaMetastoreDataSourcesSuite

Added fix for SDENT-199

---

build.gradle

Updated hive version to 1.21.2.3.1.2.1-1 from 1.21.2.3.1.2.0-4 as dependency jar removed fro the repository.
Manually Tested
NA
https://github.com/TIBCOSoftware/snappy-spark/pull/210

Added fix for build failure

---

cluster/src/test/scala/org/apache/spark/sql/store/SQLMetadataTest.scala
core/src/dunit/scala/io/snappydata/cluster/SplitClusterDUnitTestBase.scala
core/src/test/scala/org/apache/spark/sql/store/MetadataTest.scala

Code fix is in https://github.com/TIBCOSoftware/snappy-store/pull/565
Reference: https://github.com/TIBCOSoftware/snappydata/issues/1559

[GITHUB-1559]  Added test for issue #1559
